### ISSUE TITLE
Crash on server start

### ISSUE THREAD

**Issue by WORMSTweaker** [Benjamin-Norton/Neruina#10]
Hello,

My server has Neruina installed, and started perfectly well at first, but after a few reboots and hours of gameplay, the server started crashing on startup, with the attached stacktrace.
Game version is 1.19.2, Neruina is 1.1.0, Java is 17 running Fabric 0.14.22, removing Neruina fixes the issue.

I did not find any similar issues on the repo

[crash_log.txt](https://github.com/Bawnorton/Neruina/files/12642843/crash_log.txt)

**Comment by Bawnorton** [comment]
Remove Erroring Entity Remover, they're incompatible with Neruina, more precisely EER is redundant as it's functionality is already included in Neruina. I'll update the mod dependencies to clearly state that the incompatibility.
