### ISSUE TITLE
collapse-1.20.1fabric

### ISSUE THREAD

**Issue by zc1108aaa** [Benjamin-Norton/Neruina#100]
![image](https://github.com/user-attachments/assets/d7080ed8-cf1f-408f-ad6f-be3815bf3d48)
0
[crash-2024-09-04_01.20.35-server.txt](https://github.com/user-attachments/files/16852554/crash-2024-09-04_01.20.35-server.txt)
0
[latest.log](https://github.com/user-attachments/files/16852561/latest.log)

**Comment by Bawnorton** [comment]
Not caused by neruina, no obvious cause in the stack trace. Try a binary search

**Comment by zc1108aaa** [comment]
[crash-2024-09-04_02.19.32-client.txt](https://github.com/user-attachments/files/16853351/crash-2024-09-04_02.19.32-client.txt)

**Comment by Bawnorton** [comment]
Caused by nostalgic or fast quit
