### ISSUE TITLE
Hard Crash on 1.19.2

### ISSUE THREAD

**Issue by Coraline774477** [Benjamin-Norton/Neruina#101]
Minecraft: 1.19.2
Forge: 43.4.2
Neruina: 2.1.2

I'm just letting you know that Neruina is using a lot of server resources in 1.19.2 on both of my worlds in that game version just for it to do it's job to protect me from ticking entities..
I've decided to remove Neruina from ALL of my mod lists (1.19.2 and 1.20.1) because it's potentially causing performance issues and I need as much framerate (FPS and TPS) as possible..

However...
I believe that when I had my game running nonstop by accident and on purpose (forgetting to quit the game entirely after every game session or I purposely left the game running. I'll accept that as my fault to what I experienced last night which was the game freezing up on me) that Neruina continued to eat away at the server's resources because I never truly quitted the game entirely since I was only logging out and back into the world to reset my public profile key.

So what happened last night/game session on my world; Cora World: Minecraft Dungeons (1.19.2) was that I was out adventuring with my MCA Reborn villager wives (wife 2 as Silvie and potential wife 4 as Margita) to the northern unexplored regions of the world from my new home base as a relocated home from my old home that was still too close to what I nicknamed the "Death Church", which is a huge church from When Dungeons Arise mod.

When I made it to the edge of the unexplored parts of the world in the northern parts that the world wasn't loading in and all entities weren't moving, including my villager wives and I wasn't able to look into my traveler's backpack or even open the pause menu or any GUI which means the game was practically frozen and hanging...
The only way I was able to stop the game was to kill it's process in Task Manager (which I always keep it open to keep most of the background processes from restarting)...

However, before that I was looking in the log while the game was still completely frozen and hanging and I don't understand what it was saying and that ModernFix's watchdog had kicked in and did a thread dump which to me seems like that's not a good thing...

I reported my findings to ModernFix's discord and was told to get Spark to see what the heck was going on and it turns out that this mod is eating up alot of resources for it to do it's job...
Which in the spark profiler it was saying that Neruina was using about %40 of the server thread which the lettering was in orange which means not really that good... That's bad...
And I thought that MCA Reborn was the one eating up most of the server's resources but not quite compared to Neruina....

I will NOT tolerate that at all because I need as much performance as possible since I'm playing minecraft (modded) on an un-optimal machine that wasn't practically built for gaming even though on Amazon they say that it is and my parents aren't going to get me an optimal machine for quite awhile so I'm practically stuck with the ASUS Vivobook 15 for awhile...

Anyways...
Here's the log but there was no crash report because I forcfully closed the game by killing it's process in Task Manager which caused the game to not generate a crash report;

https://gist.github.com/Coraline774477/780c9c3434e6d2feca8e2293256bbdd9

Here's the Spark profile when I ran the profiler on Cora World: Minecraft Dungeons (1.19.2);

spark.lucko.me/2Wgj0ZbZL8

One more thing if you copy and paste the spark profile in your browser, When in the spark profile look in the mods section to see that this mod is causing the most amount of lag to the intergraded server which I do not tolerate that, not one bit...
Also to keep expanding in Neruina's server thread to see what's the most laggy server thread in the mod.

Btw, while I was using Spark I could've ran a new profiler action that would've been more precise than just running the profiler after installing Spark but oh well...
Ain't going to do that now 'cause I've already yetted Neruina out of my mod lists and I'm switching game versions and worlds today anyways.

**Comment by Bawnorton** [comment]
Neruina has no impact on performance #83 

You're crashing because of bad structure gen causing a deadlock in the server thread
