### ISSUE TITLE
Forge 1.20.1 Neruina Incompatibility with Dreadsteel armor mod

### ISSUE THREAD

**Issue by Luisfgm03** [Benjamin-Norton/Neruina#102]
It just crash when a player gets damage from lava or when other player hits him, i have a server with friends, the dreadsteel its a final game armor that can be crafted with some ingots from the ice and fire mod, the armor made the user invencible to lava, ice and lightning damage

**Comment by Bawnorton** [comment]
Need logs

**Comment by Luisfgm03** [comment]
one sec

**Comment by Luisfgm03** [comment]
![Captura de pantalla (793)](https://github.com/user-attachments/assets/8accc8a5-4c3c-4697-a58f-e9021695bab3)
![Captura de pantalla (792)](https://github.com/user-attachments/assets/66a064b3-bd84-4422-806a-7f92f1ebc483)
![2024-09-05_13 33 35](https://github.com/user-attachments/assets/89767fd6-2497-43f3-9b99-d27822b69037)

**Comment by Bawnorton** [comment]
Report to dreadsteel. This is not a hard crash, neruina is functioning as expected.

**Comment by Luisfgm03** [comment]
when i hit my friend with the armor it just crash
