### ISSUE TITLE
Neurina mod cause most of the tps lags on the server.

### ISSUE THREAD

**Issue by xHamak** [Benjamin-Norton/Neruina#103]
![obraz_2024-09-17_204909077](https://github.com/user-attachments/assets/758df03b-0aa4-4d05-aa75-3caed2016c4f)

Neurina mod cause most of the tps lags on the server.

![obraz_2024-09-17_204940324](https://github.com/user-attachments/assets/79b5cb99-1c22-40c4-8dc2-0d72625f424d)

**Comment by Bawnorton** [comment]
#83
