### ISSUE TITLE
ticking issues on players when playing with sky lands mod

### ISSUE THREAD

**Issue by slovinsqui** [Benjamin-Norton/Neruina#104]
there is this 1.20.1 mod that adds floating islands that I installed in a already existing world, I don´t know why this causes ticking issues only on players, resulting on neruina kicking them

idk if this would help but here´s the log

I also reported the issue on the skylands mod´s discord but there is no real answer from it´s author, a user told me that there is straight up no fix because skyland uses a weird mob kill to terrain generation system, but they were not the mod´s author.

So might as well post this here too juuust in case

server log since there were no crashes:

https://mclo.gs/cLwTcee

**Comment by slovinsqui** [comment]
sorry for bothering you but I just wanted a clear answer from the developer of any of the two mods that are causing the issue

**Comment by Bawnorton** [comment]
This log doesn't have neruina in it; although it's crashing because of cloth config being installed on the server (it's a client only mod)

**Comment by slovinsqui** [comment]
broo no waaay, lemme check

**Comment by slovinsqui** [comment]
looks like bosses of mass destruction needs cloth config to be installed

**Comment by Bawnorton** [comment]
More specifically a client-only part of cloth config is running on the server, which is crashing. Idk why, idk what the fix is. I do know that this isn't a neruina issue as neruina isn't even present so I'm gonna close this.
