### ISSUE TITLE
Too many ticking exceptions - Please help diagnose!

### ISSUE THREAD

**Issue by dogonotoughen** [Benjamin-Norton/Neruina#106]
[crashlog.txt](https://github.com/user-attachments/files/17148540/crashlog.txt)

I understand it isn't the fault of Neruina; I'm just want to understand what's happening. I'm seeing a lot of entities from the "digimod" mod, but I don't want to remove the mod. Could somebody please shed some light on what's causing the ticking entity exceptions?

**Comment by Bawnorton** [comment]
My best guess is a conflict between Alex mobs and digimon. However, the crash is an internal Mixin crash and you are also using sinytra which may be the culprit but it's unclear.
