### ISSUE TITLE
Crash when killing entity

### ISSUE THREAD

**Issue by pumkinhead456** [Benjamin-Norton/Neruina#107]
[crash-2024-10-10_09.31.18-server.txt](https://github.com/user-attachments/files/17329905/crash-2024-10-10_09.31.18-server.txt)
[debug.log](https://github.com/user-attachments/files/17329907/debug.log)
[latest.log](https://github.com/user-attachments/files/17329908/latest.log)

It is a spider that Neurina keeps finding as the culprit when I press kill entity. It just crashes.

**Comment by Bawnorton** [comment]
Crashing because https://github.com/Bawnorton/Neruina/wiki/Too-Many-Ticking-Exceptions.

Culprit is the Palladium mod
