### ISSUE TITLE
a lot of ticking enteties 

### ISSUE THREAD

**Issue by gefeshka38** [Benjamin-Norton/Neruina#109]
hello, i have a problem in minecraft modpack world, there`s a lot of mods but problem started when i added mod about scp that sometimes make an anouncemet that on next motning sunlight will kill everything exposed to it the mod name is SCP-001, "When Day Breaks" and the first morning after this anouncemet huge amount of messages about ticking enteties started to appear in chat, i deleted this mod after this and it`s been a few days after this occasion but a few messages apear sometimes even in new loaded chunks

example of error message
[text.txt](https://github.com/user-attachments/files/17351059/text.txt)

**Comment by Bawnorton** [comment]
flight conduit breaking, I'll report to them

**Comment by gefeshka38** [comment]
but how do i fix this in my world?

> flight conduit breaking, I'll report to them

**Comment by Bawnorton** [comment]
You remove the mod

**Comment by gefeshka38** [comment]
ok, thank you for answering so quickly

**Comment by Bawnorton** [comment]
Update has been published with the fix https://modrinth.com/mod/flight-conduit
