### ISSUE TITLE
[1.18.2] Failed to launch: MixinExtras error

### ISSUE THREAD

**Issue by DeshiDesu** [Benjamin-Norton/Neruina#11]
Forge 40.2.10
Neruina 1.1.1 / 1.2.0 / 1.2.1
memoryleakfix-forge-1.17+-1.1.2

**What happened:**
My client failed to load with the following message: 
> Caused by: com.llamalad7.mixinextras.sugar.impl.SugarApplicationException: Failed to apply sugar to method memoryLeakFix$captureByteBuffer(Ljava/nio/ByteBuffer;Lca/fxco/memoryleakfix/mixinextras/sugar/ref/LocalRef;)Ljava/nio/ByteBuffer; from mixin memoryleakfix.mixins.json:hugeScreenshotLeak.Minecraft_screenshotMixin in target method net/minecraft/client/Minecraft::m_167903_(Ljava/io/File;IIII)Lnet/minecraft/network/chat/Component; at instruction InjectionNode[MethodInsn [INVOKESPECIAL] net/minecraft/client/Minecraft::modifyExpressionValue$bno000$memoryLeakFix$captureByteBuffer(Ljava/nio/ByteBuffer;)Ljava/nio/ByteBuffer;]
[latest.log](https://github.com/Bawnorton/Neruina/files/12680888/latest.log)

This seemingly applies only with Neruina 1.1.1 versions and up. Other versions work as intended.

I tried recreating this error with only memoryleakfix and Neruina but it didn't fail. There may be other third party mods causing this error but debugging will be arduous because I have more than 200 mods.

**Comment by Bawnorton** [comment]
This looks like a bug with a library I'm using. I'll report it and get back to you.

**Comment by Bawnorton** [comment]
Fixed in [1.2.2](https://github.com/Bawnorton/Neruina/releases/tag/1.2.2)

**Comment by DeshiDesu** [comment]
Thank you. I just tried the new version and it worked perfectly
