### ISSUE TITLE
where do i see neruina logs?

### ISSUE THREAD

**Issue by VaporeonScripts** [Benjamin-Norton/Neruina#110]
![image](https://github.com/user-attachments/assets/589b7cb8-181b-431c-98e8-ae209f210147)

**Comment by Bawnorton** [comment]
Server log

**Comment by VaporeonScripts** [comment]
im in singleplayer

**Comment by Bawnorton** [comment]
Send your latest.log

**Comment by VaporeonScripts** [comment]
it just says that message, no log at all, but ig

**Comment by VaporeonScripts** [comment]
https://mclo.gs/hEiCnIg

**Comment by Bawnorton** [comment]
Caused by a combination of betterchunkloading and lithium

**Comment by VaporeonScripts** [comment]
I have to report it to lithium?

**Comment by Bawnorton** [comment]
Yeah probably, they'll know more. Scroll up a bit from the kick message for the crash.
