### ISSUE TITLE
Crash when trying to enter the world [Forge 1.20.1]

### ISSUE THREAD

**Issue by mpustovoi** [Benjamin-Norton/Neruina#111]
Neruina: 2.1.1-forge+1.20.1

I was testing the work of the **Sculk Horde** mod in my modpack.
When I entered the mod's dungeon, a Warden emerged next to me. A Neruina's error message appeared in the chat for a moment, after which the game crashed.
I can no longer enter this world, because when the erroring entity is loaded the crash occurs again and again.

Logs: https://mclo.gs/fCPVSof.

Crash report: https://mclo.gs/LYiP2Kx.

I'm just afraid that my friends might accidentally encounter this and lose their worlds.

**Comment by Bawnorton** [comment]
gigeresque is doing something very wrong

**Comment by mpustovoi** [comment]
Thanks for the clarification.
**Gigeresque** no longer supports 1.20.1, so I guess it will have to be removed.

**Comment by Bawnorton** [comment]
Not entirely sure if I should try to handle this gracefully; it's failing to handle because the entity that is crashing .. doesn't exist. Which makes handling it .. complicated

**Comment by Bawnorton** [comment]
Seems to be related https://github.com/cybercat-mods/gigeresque/issues/307

**Comment by mpustovoi** [comment]
> Please note, however, that due to Forge 1.20.1 brain issues, only the fabric version will be pushed, so you will need to swap from the forge-marked jar to the fabric one manually.

I see it's fixed by the developer, but it will cause problems with updates in the Modrinth App.

> 1.20.1 is abandoned and no longer updated

They didn't say that for nothing.

**Comment by mpustovoi** [comment]
Thank you again for your help.
