### ISSUE TITLE
Update to 1.21.1+

### ISSUE THREAD

**Issue by suerion** [Benjamin-Norton/Neruina#112]
Hey, could you please Update the Mod to 1.21.1 and above? 

Thanks a lot.

**Comment by Bawnorton** [comment]
Mod already supports 1.21.1

**Comment by suerion** [comment]
> Mod already supports 1.21.1

@Bawnorton oh sorry, on Modrinth, the tags are saying 1.21.

Sorry, i will close the issue ;) thanks for answere
