### ISSUE TITLE
Animation Indexing

### ISSUE THREAD

**Issue by itsdeadfrosty** [Benjamin-Norton/Neruina#114]
[latest.log](https://github.com/user-attachments/files/17606483/latest.log)

Error: IndexOutOfBoundsException in animation handling, especially on tick entities.
Impact: May lead to unexpected client behavior during animation playback for specific entities.
Potential Conflict: Seen with player-animation-lib, which may require compatibility checking.

**Comment by Bawnorton** [comment]
Duplicate of #115
