### ISSUE TITLE
Cannot join world

### ISSUE THREAD

**Issue by itsdeadfrosty** [Benjamin-Norton/Neruina#115]
i have no idea where to find N log, but i cant get into a singleplayer world w this installed

[latest.log](https://github.com/user-attachments/files/17606596/latest.log)

**Comment by Bawnorton** [comment]
Player animation lib breaking

**Comment by itsdeadfrosty** [comment]
are they incompatible? does it need something? kind of a cold quick cut response man

**Comment by Bawnorton** [comment]
No, it's breaking, it is the cause of the disconnecting

**Comment by itsdeadfrosty** [comment]
ill take it up w playerlib then. thanks.
