### ISSUE TITLE
Silent Crash when loaded alongside GroovyModLoader

### ISSUE THREAD

**Issue by ZestyBlaze** [Benjamin-Norton/Neruina#116]
Steps:
1. Install GroovyModLoader and Neurina
2. Load the game
3. The game silently crashes with an Exit Code 1, nothing in logs and nothing in crash reports

Launcher Log: [log](https://paste.gg/p/anonymous/742ba553580c4b0b8f34b571486f2c1d)

Screenshots discussing with the dev of GML:
![image](https://github.com/user-attachments/assets/be846401-7340-4b60-ac6c-841bba91c31e)

**Comment by Bawnorton** [comment]
https://discord.com/channels/313125603924639766/1128972595249819769/1306325786302615552
