### ISSUE TITLE
hire an artist to make your icon.

### ISSUE THREAD

**Issue by toastedfoxx** [Benjamin-Norton/Neruina#117]
no need to use ai bullcrap for this, especially since its at almost 1 million downloads, and you are getting income for part of something you didn't create.

**Comment by Bawnorton** [comment]
This icon was made with Substance Painter and photoshop well over a year ago and is math based. Please don't make unsubstantiated accusations, I don't condone or support the usage of AI.

https://github.com/Bawnorton/Neruina/blob/OLD-multi-version/icon/README.md
