### ISSUE TITLE
Neruina crash server

### ISSUE THREAD

**Issue by kitovoi111** [Benjamin-Norton/Neruina#118]
Forge 1.19.2
Neruina-2.1.2-forge+1.19.2.jar
[crash-2024-11-15_16.15.46-server.txt](https://github.com/user-attachments/files/17778201/crash-2024-11-15_16.15.46-server.txt)

**Comment by Bawnorton** [comment]
Fixed in 2.2.7

**Comment by NeoFolia** [comment]
Forge please.
