### ISSUE TITLE
Ticking entity killing player?

### ISSUE THREAD

**Issue by TempystWin** [Benjamin-Norton/Neruina#12]
![image](https://github.com/Bawnorton/Neruina/assets/144642542/589b3e9c-015c-4e62-a50e-4e3a6534ae1a)

Playing with a friend and suddenly it starts killing his "entity" and now cannot pick up items within the world.

**Comment by Bawnorton** [comment]
Can you send the server's latest.log please.

you can find it here https://fabricmc.net/wiki/player:tutorials:logs_ml:windows

**Comment by Bawnorton** [comment]
This release should fix that issue, a ticking player should be kicked instead of killed, but you will still have an underlying issue with the player that you will need to address as a ticking player is not good.

https://github.com/Bawnorton/Neruina/releases/tag/1.2.3
