### ISSUE TITLE
No config file for 1.21.1?

### ISSUE THREAD

**Issue by LevyWilson** [Benjamin-Norton/Neruina#121]
I installed Neruina on my ATM10 server to try to stop some of the crashes that come with a bleeding edge modpack like that, but Neruina never added a config file to the server's config directory. It's running, but I can't seem to change its settings.

**Comment by Bawnorton** [comment]
Config in 1.21+ is under the `configurable` directory

**Comment by LevyWilson** [comment]
> Config in 1.21+ is under the `configurable` directory

@Bawnorton 

There is no configurable directory. 
![image](https://github.com/user-attachments/assets/a23807f6-929b-482d-9a89-7c22c09f7240)
![image](https://github.com/user-attachments/assets/6d25761b-694b-4901-9309-6ce6bba45aef)
![image](https://github.com/user-attachments/assets/591f0732-526e-4219-85f9-f2274ca6888c)

**Comment by NikzardGG** [comment]
config folder

**Comment by LevyWilson** [comment]
> config folder

It's not there. That's pic 2, no 'configurable' directory.
