### ISSUE TITLE
Neruina not making a configurable directory

### ISSUE THREAD

**Issue by LevyWilson** [Benjamin-Norton/Neruina#122]
In relation to my last issue #121 , I can't find a `configurable` directory in which said config file would be. It seems like Neruina didn't make it. My ATM10 server is running on a Debian system under Crafty. Possibly a permissions problem? Though no other mods seem to have issue making files in the server files.

![389735307-a23807f6-929b-482d-9a89-7c22c09f7240](https://github.com/user-attachments/assets/ed11e349-f0db-492f-a4aa-3bb4f62e012d)
![389735344-6d25761b-694b-4901-9309-6ce6bba45aef](https://github.com/user-attachments/assets/6cddf8ef-0330-41b7-8c71-8104d2ed456d)
![389735395-591f0732-526e-4219-85f9-f2274ca6888c](https://github.com/user-attachments/assets/5c95c72a-6174-4a0b-8499-c2adfa840376)

**Comment by Thebigboss537** [comment]
same error, I can't find the configuration file

**Comment by NikzardGG** [comment]
config folder, the third in the first picture

**Comment by LevyWilson** [comment]
> config folder, the third in the first picture

Last issue I made @Bawnorton said it's supposed to make its own directory in 1.21+, which it clearly isn't doing.

**Comment by Bawnorton** [comment]
I am very busy atm as I am taking my exams, so I have had no time to fix this, yes its currently broken and I'll get to it when I can, likely around christmas. Apologies

**Comment by LevyWilson** [comment]
> I am very busy atm as I am taking my exams, so I have had no time to fix this, yes its currently broken and I'll get to it when I can, likely around christmas. Apologies

All good. Thanks. Take your time. I think it is still helping even running on default settings. Just can't configure it to halt erroring ticking entities and tile entities yet.

**Comment by Cr4fTJuNkiE** [comment]
I'm having the same issue. Now I can't load my world with Neruina installed because I can't change the Ticking Entity setting. Is there a premade config I can download possibly? thanks.

**Comment by Bawnorton** [comment]
Should be fixed in 2.2.5
Reverted to old config system until I can get around to fixing configurable
