### ISSUE TITLE
Config still not working for some reason

### ISSUE THREAD

**Issue by Gonkas77** [Benjamin-Norton/Neruina#123]
For some reason it's still using old config (I think). When my server crashed it said "handle_ticking_entities" was false and I'm assuming that's from the old config file. Either way there's a typo in the new config where under the "handles" path "entities" is written as "entites". Not sure if that has anything to do with it.

Server log:
![image](https://github.com/user-attachments/assets/b98710e2-364f-4a79-b486-093bc818fe79)

Config file:
![image](https://github.com/user-attachments/assets/32f19f6d-f238-4e1d-954d-61acc1250ada)

**Comment by Gonkas77** [comment]
I looked into this and apparently by setting "handle.entites" to false it now handles entities. The JSON also often for some odd reason does this where the format becomes questionable.
![image](https://github.com/user-attachments/assets/a9ae7606-dbeb-4f2b-94d8-43e724a7b1e6)

**Comment by Bawnorton** [comment]
Fixed in 2.2.5
