### ISSUE TITLE
Crash while trying to get back a returning spinning blade from bagus mobs into inventory after use

### ISSUE THREAD

**Issue by 2el222** [Benjamin-Norton/Neruina#127]
[latest.log](https://github.com/user-attachments/files/18222990/latest.log)
I used the item, upon return it crashed me out of game, now cant even login back to server without crashing, dont really know if its on neruina or bagus mobs, but both are involved in some way

**Comment by Bawnorton** [comment]
An item from minecolonies is crashing in your inventory. Hotbar slot 9

**Comment by 2el222** [comment]
[latest.log](https://github.com/user-attachments/files/18223019/latest.log)
no its not :)

**Comment by Bawnorton** [comment]
report to bagusmob, the crash is in the item rendering as well as the item ticking. Neruina catches the ticking part fine but it doesn't catch rendering crashes.
I initially read your log on my phone at an airport so it was tricky to identify exactly what the cause was.
