### ISSUE TITLE
Magic Map bug

### ISSUE THREAD

**Issue by Skulldemon68** [Benjamin-Norton/Neruina#15]
Me and my Friends started a new Mc Server with the Better Mc modpack, as soon as i entered the Twighlight Forest and used the Magic Map i got Kicked and now i cant Join anymore. Anything i can do so i can join again?

**Comment by Bawnorton** [comment]
Bug with moonlight lib, update it. Neruina kicking you is not a bug with Neruina, it's what it's supposed to do. By kicking the player it stops the server from hard crashing, potentially losing you progress.
