### ISSUE TITLE
Ticking Crash...Player?

### ISSUE THREAD

**Issue by TemptingDread** [Benjamin-Norton/Neruina#18]
https://pastebin.com/Fg5F2Zsq

**Comment by Bawnorton** [comment]
Neruina cannot handle ticking player exceptions in single player worlds. This appears to be caused by LambdaDynamicLights

**Comment by TemptingDread** [comment]
ok so what should i do? I really want to use Ars Noveau. Should I delete it? I can't even find Lambda in the mod list....

edit: ok I found the file but it comes back even after I delete it when I restart minecraft

edit2: Nvm it was a mod called Ryoamiclights that was in the modpack and removed it.
