### ISSUE TITLE
Crashing with Ars Noveau (1.20.1)

### ISSUE THREAD

**Issue by oaceloragm** [Benjamin-Norton/Neruina#19]
I've tried to make a modpack I'm running work with Ars Noveau for a while but it always crash. It supposedly occurs in an interaction between both mods, according to the crash reports. I've tried a bunch of versions of both of them but got no positive results.
[crash-2023-10-18_07.34.16-client.txt](https://github.com/Bawnorton/Neruina/files/13013128/crash-2023-10-18_07.34.16-client.txt)

**Comment by Bawnorton** [comment]
Identical to #18
