### ISSUE TITLE
is it okay that this shows up as 50% in spark

### ISSUE THREAD

**Issue by inikishev** [Benjamin-Norton/Neruina#2]
https://spark.lucko.me/LpAMX5iyVE

I am assuming it replaces entity ticks so that they show up as this mods ticks. Or is there something broken about my game?
![image](https://github.com/Benjamin-Norton/Neruina/assets/76593873/d4730b7b-2fae-425a-9e2e-9d3ad09bc79e)

**Comment by Bawnorton** [comment]
Yes this mod wraps all ticking methods, spark will read this incorrectly and assume that neruina is the one ticking but it is still the vanilla game that is ticking.
