### ISSUE TITLE
(Request) Will there be 1.20.2 support?

### ISSUE THREAD

**Issue by Tursiops-G** [Benjamin-Norton/Neruina#22]
Thanks.

**Comment by Bawnorton** [comment]
Waiting for Architectury to support NeoForge 1.20.2 to officially support it, the latest version should work on 1.20.2 fabric but it might not work on 1.20.2 forge because of the split. Try it and see.

**Comment by Tursiops-G** [comment]
(Sorry for the delay).
Fabric version Works (so far, at least it doesn't crash itself) on Fabric 1.20.2.  ;)
(Of Course, I Haven't yet encountered a Ticking item/entity error.}

However, the (Neo)Forge version fails to load in NeoForge 1.20.2 with a JavaFML version error.
Logdump:
https://mclo.gs/kiigeVX

(Of Course, I only find this out when having to add it to a Neoforge instance with a Ticking-Bricked World)...  :(

**Comment by Bawnorton** [comment]
As expected. This will need a dedicated update, I'll let you know when Architectury supports NeoForge

**Comment by Tursiops-G** [comment]
Thanks.

(If you need a Beta tester, I already have a Bricked world ready to go for it),,, ;)

**Comment by Bawnorton** [comment]
Added in 2.0.0-beta.1
