### ISSUE TITLE
Mod kills ships from Small Ship's mod while scrolling inventory.

### ISSUE THREAD

**Issue by Magmabot16** [Benjamin-Norton/Neruina#23]
While playing Prominence II, this mod has deleted my ships multiple times. The steps to replicate the issue I'm experiencing are simple enough: get in a spruce brigg, go into the brigg's inventory, scroll between inventory screens.
![2023-10-22_09 45 40](https://github.com/Bawnorton/Neruina/assets/69100331/5f625f69-8047-44ea-9e38-8ea3597af95f)

**Comment by Bawnorton** [comment]
Neruina deleting entities is intended behaviour, it's designed to stop your world from bricking, if Neruina didn't kill that entity, you would be locked out of your world.
Report this to the developer of the mod that adds the `Brigg` entity.

**Comment by Magmabot16** [comment]
alright I'll send them a report

**Comment by V-lpen** [comment]
Hi there, Ive done some more testing and I can confirm theres no ticking entity crash without neurina, and i believe it to be a false positive. Is there plans for a whitelist?

**Comment by Bawnorton** [comment]
Neruina cannot false positive, it is functionally impossible. 
Neruina catches error propagation right before the Minecraft crash sequence begins, if Neruina doesn't catch the propagating error, the game will crash, every time.

<details>
<summary>Code analysis if you're not convinced</summary>

this method [here](https://github.com/Bawnorton/Neruina/blob/multi-version/common/src/main/java/com/bawnorton/neruina/handler/NeruinaTickHandler.java#L119) is what runs minecraft's entity ticking.

that `operation.call` is the reference to `tickConsumer.accept(entity)`, they are the same method in a sense.

<img width="801" alt="Screenshot 2023-11-04 at 18 50 42" src="https://github.com/Bawnorton/Neruina/assets/18416784/d73fe54e-d3b9-4e62-a0b8-811e30843f91">

if Neruina does not catch the throwable first, it gets passed to the crash report creator, which crashes the game.
</details>
