### ISSUE TITLE
Please add a config to change the messages that print to chat or just simply make it so that only OP'd players can see them

### ISSUE THREAD

**Issue by Knack117** [Benjamin-Norton/Neruina#25]
Issue/suggestion in title of post. 

Thank you for a wonderful mod, it is just really awkward to use on a PvP server.

**Comment by Bawnorton** [comment]
I'll look into adding a config

**Comment by Knack117** [comment]
> I'll look into adding a config

Thanks!! <3

**Comment by Bawnorton** [comment]
Broadcast option added in 1.3.0
