### ISSUE TITLE
Issue with Bountiful Mod

### ISSUE THREAD

**Issue by TheCavemanOfficial** [Benjamin-Norton/Neruina#26]
Running this in Single Player does not cause any issue, however when placed on a server this caused a player to get locked out of the server upon claiming a reward for a bounty board. Deleting the playerdata was the ONLY solution here. I have included the log file from the server, hope this helps.
[latest.log](https://github.com/Bawnorton/Neruina/files/13255267/latest.log)

**Comment by Bawnorton** [comment]
~~Bountiful is using client-only code in common source which will crash when used on a server,~~ this is not related to Neruina

It's likely that the underlying cause is Create: Sweets and Treats that doesn't respect the logical sides and calls client-only methods when it shouldn't
