### ISSUE TITLE
Respawn

### ISSUE THREAD

**Issue by SolidStateNetwork** [Benjamin-Norton/Neruina#27]
Please add that if the mod kills an entity (Villager). Try to spawn a new one.

**Comment by Bawnorton** [comment]
This is a terrible idea as sometimes the entity just existing is what causes it to crash, this would lead to infinite, repeated crashes. Instead fix the underlying problem and it won't happen again, it'll be in your log.

**Comment by SolidStateNetwork** [comment]
Ok thanks for the really fast respond
