### ISSUE TITLE
1.20.1 Client Crash on exiting the nether via a new nether portal.

### ISSUE THREAD

**Issue by ProsperCraft** [Benjamin-Norton/Neruina#28]
https://gist.github.com/ProsperCraft/985a3b6158db56eb6e2e1d1c114f209a

Modpack - TownCraft for 1.20.1 (Beta 0.84)

**Comment by Bawnorton** [comment]
Caused by `majruszsaccessories`, Neruina cannot stop crashes from happening when the player is the entity that ticks and you're in a single-player world. This is not a bug.

**Comment by ProsperCraft** [comment]
I forgot to mention that this was on a multiplayer server, not single player.
