### ISSUE TITLE
Neruina eats my ores in alloy forgery mod

### ISSUE THREAD

**Issue by Patryboy** [Benjamin-Norton/Neruina#29]
Whenever I try to smelt an ore in an alloy forge in Minecraft medieval mod pack, it says in chat that it is a ticking error, completely eating my ores. This renders the alloy forge useless. All pillagers in my world are considered ticking entities and dissappear whenever I get close to them.

**Comment by Bawnorton** [comment]
Neruina doing its job is not a bug, you'll want to share your log with the MMC discord server to get support. 
Neruina is stopping your game from crashing and world from becoming bricked.
