### ISSUE TITLE
(Fabric 1.18.2) Incompatibility with "Observable"

### ISSUE THREAD

**Issue by Laskyyy** [Benjamin-Norton/Neruina#3]
**Describe the Bug**

Minecraft will crash on startup when both the 'Observable' and 'Neruina' mods are present.

**Fabric Version**
0.14.21

**Mod Version**
1.0.0 (Neruina)
2.2.3 (Observable)
 https://modrinth.com/mod/observable

**Minecraft Version**
1.18.2

**Other Mods**
Architectury
Fabric API

**Latest.log file of most recent boot**
[latest.log](https://github.com/Benjamin-Norton/Neruina/files/11886469/latest.log)

**Further context**
Neruina has honestly saved me hours of time troubleshooting from bricked saves due to block entities on my public servers over on Create: Astral, however it has had to be run without observable which is undoubtably the most convenient 'lag-goggles' type mod when optimising block tps on hectic servers. (especially regarding create which hog way too much!)

In the event that it *would* be possible to have compatibilty between these two, i'd truly regard it as my lifesaver!

If this is not fixable on your end, shoot a message and i'll pop it on the observable github as well. It's truly a blessing to those of us who have long-playtime modded worlds & servers.❤️

**Comment by Bawnorton** [comment]
Yeah I'll give this a look, shouldn't be too difficult to add a compatibility patch

**Comment by Bawnorton** [comment]
Should be fixed in 1.0.1 fabric 1.18.2
