### ISSUE TITLE
Ticking Crash - Entity??? Player???? 

### ISSUE THREAD

**Issue by LemonEggs** [Benjamin-Norton/Neruina#31]
https://pastebin.com/skfUFuuw

❤️ it's probably caused by an arrow from l2complements being deleted? i think
world crashes immediately

**Comment by LemonEggs** [comment]
nvm actually! It was skill tree needing an update since it fought with l2, neruina was just trying its best

**Comment by grahamfoxrollup** [comment]
null values on the abstractArrow cause ticking players that cant be kicked
