### ISSUE TITLE
Caught ClassCastException but did not supply helpful logs

### ISSUE THREAD

**Issue by burdoto** [Benjamin-Norton/Neruina#34]
A falling anvil caused a ClassCastException due to some mod incompatibility.
However, the logs weren't very helpful; as both `latest.log` and `debug.log` only stated this:
```
[07Jan2024 08:28:45.523] [Server thread/WARN] [neruina/]: Server: [Neruina]: Caught Ticking Entity [Falling Anvil] at position [x=17200.0, y=77.0, z=9031.0]. It has been killed.
java.lang.ClassCastException: null
```
There was no Stacktrace in either of them.

**Comment by Bawnorton** [comment]
Can you send your latest.log anyway, might be some other info. An empty stacktrace is very odd.
You can disable Neruina's handling in it's config if you want it to hard crash and try to see if that gives a clearer indication of what happened

**Comment by Bawnorton** [comment]
No response
