### ISSUE TITLE
Getting this annoying crash every so often.

### ISSUE THREAD

**Issue by LucioMagno** [Benjamin-Norton/Neruina#36]
Error: com.bawnorton.neruina.exception.DoNotHandleException: java.lang.RuntimeException: Failed to locate any affixes for air{null} with category LootCategory[curios:aether_gloves] and rarity LootRarity{apotheosis:rare}.

**Comment by Bawnorton** [comment]
Post the full log

**Comment by LucioMagno** [comment]
The issue was with Apothic Curios mod! Cheers
