### ISSUE TITLE
Cannot assign field "fallResetY" because "result" is null (Crash)

### ISSUE THREAD

**Issue by TheLemzz** [Benjamin-Norton/Neruina#38]
Fabric 0.14.21 1.20.1

Description: Ticking entity

com.bawnorton.neruina.exception.DoNotHandleException: java.lang.NullPointerException: Cannot assign field "fallResetY" because "result" is null
	at com.bawnorton.neruina.handler.NeruinaTickHandler.handleErroredEntity(NeruinaTickHandler.java:151)
	at com.bawnorton.neruina.handler.NeruinaTickHandler.safelyTickEntities$notTheCauseOfTickLag(NeruinaTickHandler.java:112)
	at net.minecraft.class_1937.wrapOperation$god000$neruina$catchTickingEntities(class_1937.java:13548)
	at net.minecraft.class_1937.method_18472(class_1937.java:480)
	at net.minecraft.class_3218.method_31420(class_3218.java:385)
	at net.minecraft.class_5574.method_31791(class_5574.java:54)
	at net.minecraft.class_3218.method_18765(class_3218.java:353)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:897)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:824)
	at net.minecraft.class_1132.method_3748(class_1132.java:105)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:671)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.NullPointerException: Cannot assign field "fallResetY" because "result" is null
	at net.minecraft.class_1297.handler$gcp000$minecells$injectMoveToWorld(class_1297.java:20888)
	at net.minecraft.class_1297.method_5731(class_1297.java:2698)
	at net.minecraft.class_1542.method_5731(class_1542.java:391)
	at net.minecraft.class_1297.method_18379(class_1297.java:2267)
	at net.minecraft.class_1297.method_5670(class_1297.java:494)
	at com.bawnorton.neruina.handler.NeruinaTickHandler.handleErroredEntity(NeruinaTickHandler.java:148)
	... 12 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at com.bawnorton.neruina.handler.NeruinaTickHandler.handleErroredEntity(NeruinaTickHandler.java:151)
	at com.bawnorton.neruina.handler.NeruinaTickHandler.safelyTickEntities$notTheCauseOfTickLag(NeruinaTickHandler.java:112)
	at net.minecraft.class_1937.wrapOperation$god000$neruina$catchTickingEntities(class_1937.java:13548)
	at net.minecraft.class_1937.method_18472(class_1937.java:480)
	at net.minecraft.class_3218.method_31420(class_3218.java:385)
	at net.minecraft.class_5574.method_31791(class_5574.java:54)
	at net.minecraft.class_3218.method_18765(class_3218.java:353)
Mixins in Stacktrace:
	net.minecraft.class_1937:
		me.jellysquid.mods.lithium.mixin.alloc.chunk_random.WorldMixin (lithium.mixins.json)
		com.ishland.c2me.notickvd.mixin.MixinWorld (c2me-notickvd.mixins.json)
		io.github.fabricators_of_create.porting_lib.entity.mixin.LevelMixin (porting_lib_entity.mixins.json)
		me.jellysquid.mods.lithium.mixin.entity.collisions.intersection.WorldMixin (lithium.mixins.json)
		io.github.fabricators_of_create.porting_lib.transfer.mixin.common.LevelMixin (porting_lib_transfer.mixins.json)
		party.lemons.biomemakeover.mixin.multipart.LevelMixin (biomemakeover-common.mixins.json)
		io.github.fabricators_of_create.porting_lib.mixin.common.LevelMixin (porting_lib_base.mixins.json)
		com.github.mim1q.minecells.mixin.world.WorldMixin (minecells.mixins.json)
		net.fabricmc.fabric.mixin.event.lifecycle.WorldMixin (fabric-lifecycle-events-v1.mixins.json)
		dev.architectury.mixin.fabric.MixinLevel (architectury.mixins.json)
		ca.spottedleaf.starlight.mixin.common.world.LevelMixin (starlight.mixins.json)
		me.jellysquid.mods.lithium.mixin.util.block_entity_retrieval.WorldMixin (lithium.mixins.json)
		dev.onyxstudios.cca.mixin.world.common.MixinWorld (mixins.cardinal_components_world.json)
		org.betterx.betterend.mixin.common.LevelMixin (betterend.mixins.common.json)
		com.ishland.c2me.fixes.worldgen.threading_issues.mixin.threading_detections.random_instances.MixinWorld (c2me-fixes-worldgen-threading-issues.mixins.json)
		me.jellysquid.mods.lithium.mixin.block.hopper.WorldMixin (lithium.mixins.json)
		me.jellysquid.mods.lithium.mixin.world.inline_block_access.WorldMixin (lithium.mixins.json)
		me.jellysquid.mods.lithium.mixin.world.chunk_access.WorldMixin (lithium.mixins.json)
		com.ishland.c2me.opts.scheduling.mixin.mid_tick_chunk_tasks.MixinWorld (c2me-opts-scheduling.mixins.json)
		net.blay09.mods.balm.mixin.LevelMixin (balm.mixins.json)
		me.jellysquid.mods.lithium.mixin.world.block_entity_ticking.sleeping.WorldMixin (lithium.mixins.json)
		com.bawnorton.neruina.mixin.WorldMixin (neruina-common.mixins.json)
		eu.pb4.polymer.common.mixin.WorldAccessor (polymer-common.mixins.json)
		fuzs.puzzleslib.mixin.LevelFabricMixin (puzzleslib.fabric.mixins.json)
		xaero.map.mixin.MixinWorld (xaeroworldmap.mixins.json)
		me.jellysquid.mods.lithium.mixin.world.inline_height.WorldMixin (lithium.mixins.json)
	net.minecraft.class_3218:
		xaero.map.mixin.MixinServerWorld (xaeroworldmap.mixins.json)
		net.fabricmc.fabric.mixin.lookup.ServerWorldMixin (fabric-api-lookup-api-v1.mixins.json)
		net.barribob.boss.mixin.ExplosionMixin (bosses.mixins.json)
		dev.architectury.mixin.fabric.MixinServerLevel (architectury.mixins.json)
		n643064.apocalypse.mixin.ServerWorldMixin (apocalypse.mixins.json)
		dev.onyxstudios.cca.mixin.chunk.common.MixinServerWorld (mixins.cardinal_components_chunk.json)
		org.betterx.betterend.mixin.common.ServerLevelMixin (betterend.mixins.common.json)
		elocindev.deuf_refabricated.mixin.ServerWorldMixin (deuf.mixins.json)
		com.yungnickyoung.minecraft.betterdeserttemples.mixin.ServerLevelMixin (betterdeserttemples.mixins.json)
		net.spell_engine.mixin.arrow.ServerWorldArrows (spell_engine.mixins.json)
		net.rpgdifficulty.mixin.ServerWorldMixin (rpgdifficulty.mixins.json)
		io.github.lucaargolo.seasons.mixin.ServerWorldMixin (seasons.mixins.json)
		me.jellysquid.mods.lithium.mixin.entity.inactive_navigations.ServerWorldMixin (lithium.mixins.json)
		io.github.fabricators_of_create.porting_lib.transfer.mixin.common.ServerLevelMixin (porting_lib_transfer.mixins.json)
		me.jellysquid.mods.lithium.mixin.world.block_entity_ticking.sleeping.ServerWorldMixin (lithium.mixins.json)
		ca.spottedleaf.starlight.mixin.common.world.ServerWorldMixin (starlight.mixins.json)
		eu.pb4.graves.mixin.ServerWorldMixin (universal-graves.mixins.json)
		com.ishland.c2me.opts.scheduling.mixin.shutdown.MixinServerWorld (c2me-opts-scheduling.mixins.json)
		org.betterx.bclib.mixin.common.ServerLevelMixin (bclib.mixins.common.json)
		me.jellysquid.mods.lithium.mixin.profiler.ServerWorldMixin (lithium.mixins.json)
		com.faboslav.friendsandfoes.mixin.ServerWorldMixin (friendsandfoes-common.mixins.json)
		net.projectile_damage.mixin.ServerWorldMixin (projectile_damage.mixins.json)
		com.natamus.collective.fabric.mixin.ServerLevelMixin (collective_fabric.mixins.json)
		party.lemons.biomemakeover.mixin.multipart.ServerLevelMixin (biomemakeover-common.mixins.json)
		io.github.fabricators_of_create.porting_lib.entity.mixin.ServerLevelMixin (porting_lib_entity.mixins.json)
		me.jellysquid.mods.lithium.mixin.alloc.chunk_random.ServerWorldMixin (lithium.mixins.json)
		dev.onyxstudios.cca.mixin.entity.common.MixinServerWorld (mixins.cardinal_components_entity.json)
		com.faboslav.friendsandfoes.mixin.ServerWorldAccessor (friendsandfoes-common.mixins.json)
		fuzs.puzzleslib.mixin.ServerLevelFabricMixin (puzzleslib.fabric.mixins.json)
		net.spell_engine.mixin.ServerWorldMixin (spell_engine.mixins.json)
		fuzs.leavesbegone.mixin.ServerLevelMixin (leavesbegone.common.mixins.json)
		eu.pb4.polymer.core.mixin.entity.ServerWorldAccessor (polymer-core.mixins.json)
		me.jellysquid.mods.lithium.mixin.util.entity_movement_tracking.ServerWorldAccessor (lithium.mixins.json)
		alternate.current.mixin.ServerLevelMixin (alternate-current.mixins.json)
		dev.onyxstudios.cca.mixin.world.common.MixinServerWorld (mixins.cardinal_components_world.json)
		eu.pb4.polymer.virtualentity.mixin.block.ServerWorldMixin (polymer-virtual-entity.mixins.json)
		net.adventurez.mixin.ServerWorldMixin (adventurez.mixins.json)
		party.lemons.taniwha.mixin.level.data.ServerLevelMixin (taniwha-common.mixins.json)
		com.bawnorton.neruina.mixin.ServerWorldMixin (neruina-common.mixins.json)
		com.ishland.c2me.opts.scheduling.mixin.mid_tick_chunk_tasks.MixinServerWorld (c2me-opts-scheduling.mixins.json)
		me.jellysquid.mods.lithium.mixin.chunk.entity_class_groups.ServerWorldAccessor (lithium.mixins.json)
		com.cupboard.mixin.ServerAddEntityMixin (cupboard.mixins.json)
		ml.pkom.mcpitanlibarch.mixin.ServerWorldTimer (mcpitanlibarch-common.mixins.json)
		corgitaco.corgilib.mixin.MixinServerLevel (corgilib.mixins.json)
		net.fabricmc.fabric.mixin.event.lifecycle.ServerWorldMixin (fabric-lifecycle-events-v1.mixins.json)
	net.minecraft.class_5574:
		me.jellysquid.mods.lithium.mixin.collections.entity_ticking.EntityListMixin (lithium.mixins.json)

-- Entity being ticked --

**Comment by Bawnorton** [comment]
Report to Minecells
