### ISSUE TITLE
[1.20.1] Crash on world creation

### ISSUE THREAD

**Issue by MrKashew** [Benjamin-Norton/Neruina#4]
https://gist.github.com/MrKashew/c032995782c1dab5000b5354559413bd

**Comment by Bawnorton** [comment]
Hmmm, you appear to have downloaded a version that I thought I'd removed as it crashes. Where did you download this one from? The latest 1.0.1+1.20 forge from curseforge should not have this issue.

**Comment by Bawnorton** [comment]
Version has been replaced, I had uploaded the wrong file to modrinth, the new one does not have this issue.
