### ISSUE TITLE
(1.18.2) Feature Request: Remove Invalid Entity Rotation Entities

### ISSUE THREAD

**Issue by I2pRandom** [Benjamin-Norton/Neruina#41]
Can we get a Feature, to automatically remove Entities throwing the error 
`[dimthread_the_end/ERROR] [minecraft/Util]: Invalid entity rotation: NaN, discarding.`

**Comment by Bawnorton** [comment]
Does this crash or brick the game? I've not come across this error before

**Comment by Bawnorton** [comment]
No response
