### ISSUE TITLE
1.20.1 The game won't start in the modpack

### ISSUE THREAD

**Issue by TheDoffee** [Benjamin-Norton/Neruina#42]
[latest.log](https://github.com/Bawnorton/Neruina/files/14178263/latest.log)

**Comment by Bawnorton** [comment]
This crash is caused by Ryoamiclights-0.1.6+1.20.1

Side note if you want Neruina to run then you will likely need to downgrade forge loader to 47.1.3 as the current version does not officially support forge after the split.
