### ISSUE TITLE
Neruina Caught Exception: Apotheosis + Super Bosses + Neruina (Loot Apotheosis Crash Item)

### ISSUE THREAD

**Issue by Krimatoria** [Benjamin-Norton/Neruina#43]
Minecraft 1.19.2 
Forge 43.3.5

Apotheosis-1.19.2-6.4.1.jar
Apotheotic_additions1.0.2_v1.19.2.jar
ApothicCurios-1.19.2-1.0.3.jar
[1.19.2][Forge] RPG-HUD-3.10.1.jar
neruina-1.3.0-forge+1.18.2-1.20.1.jar

The code of the log file with the problem at the end.

### What Super Duper looks like - they don't have a visual change, you need [1.19.2][Forge] RPG-HUD-3.10.1.jar to see them, hover over them with the mouse and there will be a signature.

The [picture ](https://www.curseforge.com/minecraft/mc-mods/super-bosses)is taken from the Curseforge mod website 
![image](https://github.com/Bawnorton/Neruina/assets/106809386/0ee996fc-36ae-4c50-a152-af9523330939)

I found the relationship of the problem and what causes it. The [**SuperBoss**](https://www.curseforge.com/minecraft/mc-mods/super-bosses) mod that I added to the build where creepers are enhanced with the [Enhanced AI](https://www.curseforge.com/minecraft/mc-mods/enhanced-ai) mod (their explosion force is greater than usual) strengthens them even more by generating colossal explosions, but this does not cause problems or crashes of the game until the Apotheosis mod is added, it adds its loot to mobs.

The [Neruina ](https://www.curseforge.com/minecraft/mc-mods/neruina)mod was already installed when **SuperBoss** was added and I tested it on superplanes, I never had the creeper essence removed before the explosion.

The problem does not always arise. Most likely, this is due to the presence or non-presence of a certain item in the creeper at Apotheosis.

![2024-02-08_23 34 09](https://github.com/Bawnorton/Neruina/assets/106809386/95f1d2af-2db4-4fad-9360-3a66f8ca7d06)
![2024-02-08_23 08 35](https://github.com/Bawnorton/Neruina/assets/106809386/6da4d297-3082-45eb-be7e-2e9cb9e4da75)
![2024-02-08_23 08 38](https://github.com/Bawnorton/Neruina/assets/106809386/e657cdce-704d-46dc-b8aa-b4ff8709b857)
![2024-02-08_23 18 12](https://github.com/Bawnorton/Neruina/assets/106809386/fee61a84-44ab-4c16-8450-526f1b3f42c1)
![2024-02-08_23 18 14](https://github.com/Bawnorton/Neruina/assets/106809386/4638644b-43f2-46c0-a80a-797d08091df2)
![2024-02-08_23 33 18](https://github.com/Bawnorton/Neruina/assets/106809386/5709dbfe-52b8-4004-a198-1504116498c2)
![2024-02-08_23 33 44](https://github.com/Bawnorton/Neruina/assets/106809386/4c26ea4b-8968-4cdc-8146-78c8bae65220)
![2024-02-08_23 37 35](https://github.com/Bawnorton/Neruina/assets/106809386/598a6b52-7ada-4774-b6cb-56d1b0191e54)

I added the problem code from the log file below. The problem arises when charged creepers explode, both ordinary ones and from the **SuperBoss** mod (**SuperBoss** - _the mod itself does not add mob eggs, this is important_)

How to check it. You need a **SuperBoss** mod, it needs 4 library mods, **Enhanced AI** 1 library [InsaneLib](https://www.curseforge.com/minecraft/mc-mods/insanelib): 

1. Pehkui-3.7.11+1.19.2- forge.jar, 
2. MobsPropertiesRandomness-4.2.3-mc1.19.2.jar, 
3. lootjs-forge-1.19.2-2.9.1.jar, 
4. kubejs-forge-1902.6.2-build.59.jar

There are no SuperBoss **eggs**, so you just take the egg of an ordinary creeper and spawn it until you have a SuperDuper creeper or its lightning-charged version.

You need a Charged SuperDuper or regular SuperDuper - precisely because their power is huge.

Yes, sometimes you need to wake him up a lot of times for him to appear. You set it on fire with a flint and in the event of an explosion, which will not happen, it will be prevented by Neruina with a message about the removal of the ticking entity. When playing on a server of 3 people, this caused a crash from the server. Although Neruina was created so as not to break the game, apparently departure is the best option.

Related to Common and Uncommon items.
I do not know which item adds Apotheosis to creepers, but the Log says about these categories of items:

[Server thread/WARN] [neruina/]: Neruina Caught Exception
6676 | java.lang.RuntimeException: Failed to locate any affixes for air{null} with category LootCategory[curios:back] and rarity LootRarity{common}.
6677 | at shadows.apotheosis.adventure.loot.LootController.createLootItem(LootController.java:71) ~[Apotheosis-1.19.2-6.4.1.jar%23406!/:6.4.1]
6678 | at shadows.apotheosis.adventure.loot.LootController.createLootItem(LootController.java:40) ~[Apotheosis-1.19.2-6.4.1.jar%23406!/:6.4.1]
6679 | at shadows.apotheosis.adventure.loot.AffixConvertLootModifier.doApply(AffixConvertLootModifier.java:37) ~[Apotheosis-1.19.2-6.4.1.jar%23406!/:6.4.1]

[Server thread/WARN] [neruina/]: Neruina Caught Exception
6713 | java.lang.RuntimeException: Failed to locate any affixes for air{null} with category LootCategory[curios:back] and rarity LootRarity{uncommon}.
6714 | at shadows.apotheosis.adventure.loot.LootController.createLootItem(LootController.java:71) ~[Apotheosis-1.19.2-6.4.1.jar%23406!/:6.4.1]
6715 | at shadows.apotheosis.adventure.loot.LootController.createLootItem(LootController.java:40) ~[Apotheosis-1.19.2-6.4.1.jar%23406!/:6.4.1]
6716 | at shadows.apotheosis.adventure.loot.AffixConvertLootModifier.doApply(AffixConvertLootModifier.java:37) ~[Apotheosis-1.19.2-6.4.1.jar%23406!/:6.4.1]

![2024-02-08_23 34 23](https://github.com/Bawnorton/Neruina/assets/106809386/7ad77e8e-bed8-4635-a5c9-5abb2f2ecb29)

[08Feb2024 23:04:06.861] [Server thread/WARN] [neruina/]: Neruina Caught Exception
6713 | java.lang.RuntimeException: Failed to locate any affixes for air{null} with category LootCategory[curios:back] and rarity LootRarity{uncommon}.
6714 | at shadows.apotheosis.adventure.loot.LootController.createLootItem(LootController.java:71) ~[Apotheosis-1.19.2-6.4.1.jar%23406!/:6.4.1]
6715 | at shadows.apotheosis.adventure.loot.LootController.createLootItem(LootController.java:40) ~[Apotheosis-1.19.2-6.4.1.jar%23406!/:6.4.1]
6716 | at shadows.apotheosis.adventure.loot.AffixConvertLootModifier.doApply(AffixConvertLootModifier.java:37) ~[Apotheosis-1.19.2-6.4.1.jar%23406!/:6.4.1]
6717 | at net.minecraftforge.common.loot.LootModifier.apply(LootModifier.java:58) ~[forge-1.19.2-43.3.5-universal.jar%23674!/:?]
6718 | at net.minecraftforge.common.ForgeHooks.modifyLoot(ForgeHooks.java:1320) ~[forge-1.19.2-43.3.5-universal.jar%23674!/:?]
6719 | at net.minecraft.world.level.storage.loot.LootTable.m_230922_(LootTable.java:90) ~[client-1.19.2-20220805.130853-srg.jar%23669!/:?]
6720 | at net.minecraft.world.entity.LivingEntity.m_7625_(LivingEntity.java:1374) ~[client-1.19.2-20220805.130853-srg.jar%23669!/:?]
6721 | at net.minecraft.world.entity.Mob.m_7625_(Mob.java:483) ~[client-1.19.2-20220805.130853-srg.jar%23669!/:?]
6722 | at net.minecraft.world.entity.LivingEntity.m_6668_(LivingEntity.java:1339) ~[client-1.19.2-20220805.130853-srg.jar%23669!/:?]
6723 | at net.minecraft.world.entity.LivingEntity.m_6667_(LivingEntity.java:1298) ~[client-1.19.2-20220805.130853-srg.jar%23669!/:?]
6724 | at net.minecraft.world.entity.LivingEntity.m_6469_(LivingEntity.java:1155) ~[client-1.19.2-20220805.130853-srg.jar%23669!/:?]
6725 | at net.minecraft.world.level.Explosion.m_46061_(Explosion.java:203) ~[client-1.19.2-20220805.130853-srg.jar%23669!/:?]
6726 | at net.minecraft.server.level.ServerLevel.m_7703_(ServerLevel.java:996) ~[client-1.19.2-20220805.130853-srg.jar%23669!/:?]
6727 | at net.minecraft.world.level.Level.m_46511_(Level.java:485) ~[client-1.19.2-20220805.130853-srg.jar%23669!/:?]
6728 | at net.minecraft.world.entity.monster.Creeper.m_32315_(Creeper.java:225) ~[client-1.19.2-20220805.130853-srg.jar%23669!/:?]
6729 | at net.minecraft.world.entity.monster.Creeper.m_8119_(Creeper.java:145) ~[client-1.19.2-20220805.130853-srg.jar%23669!/:?]
6730 | at net.minecraft.server.level.ServerLevel.m_8647_(ServerLevel.java:658) ~[client-1.19.2-20220805.130853-srg.jar%23669!/:?]
6731 | at net.minecraft.world.level.Level.mixinextras$bridge$accept$138(Level.java) ~[client-1.19.2-20220805.130853-srg.jar%23669!/:?]
6732 | at com.bawnorton.neruina.handler.NeruinaTickHandler.safelyTickEntities$notTheCauseOfTickLag(NeruinaTickHandler.java:115) ~[neruina-1.3.0-forge+1.18.2-1.20.1.jar%23572!/:?]
6733 | at net.minecraft.world.level.Level.wrapOperation$ckf000$catchTickingEntities(Level.java:3038) ~[client-1.19.2-20220805.130853-srg.jar%23669!/:?]
6734 | at net.minecraft.world.level.Level.m_46653_(Level.java:457) ~[client-1.19.2-20220805.130853-srg.jar%23669!/:?]
6735 | at net.minecraft.server.level.ServerLevel.m_184063_(ServerLevel.java:323) ~[client-1.19.2-20220805.130853-srg.jar%23669!/:?]
6736 | at net.minecraft.world.level.entity.EntityTickList.m_156910_(EntityTickList.java:54) ~[client-1.19.2-20220805.130853-srg.jar%23669!/:?]
6737 | at net.minecraft.server.level.ServerLevel.m_8793_(ServerLevel.java:303) ~[client-1.19.2-20220805.130853-srg.jar%23669!/:?]
6738 | at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:866) ~[client-1.19.2-20220805.130853-srg.jar%23669!/:?]
6739 | at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:806) ~[client-1.19.2-20220805.130853-srg.jar%23669!/:?]
6740 | at net.minecraft.client.server.IntegratedServer.m_5705_(IntegratedServer.java:84) ~[client-1.19.2-20220805.130853-srg.jar%23669!/:?]
6741 | at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:654) ~[client-1.19.2-20220805.130853-srg.jar%23669!/:?]
6742 | at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:244) ~[client-1.19.2-20220805.130853-srg.jar%23669!/:?]
6743 | at java.lang.Thread.run(Unknown Source) [?:?]

[Server thread/WARN] [neruina/]: Neruina Caught Exception
6676 | java.lang.RuntimeException: Failed to locate any affixes for air{null} with category LootCategory[curios:back] and rarity LootRarity{common}.
6677 | at shadows.apotheosis.adventure.loot.LootController.createLootItem(LootController.java:71) ~[Apotheosis-1.19.2-6.4.1.jar%23406!/:6.4.1]
6678 | at shadows.apotheosis.adventure.loot.LootController.createLootItem(LootController.java:40) ~[Apotheosis-1.19.2-6.4.1.jar%23406!/:6.4.1]
6679 | at shadows.apotheosis.adventure.loot.AffixConvertLootModifier.doApply(AffixConvertLootModifier.java:37) ~[Apotheosis-1.19.2-6.4.1.jar%23406!/:6.4.1]
6680 | at net.minecraftforge.common.loot.LootModifier.apply(LootModifier.java:58) ~[forge-1.19.2-43.3.5-universal.jar%23674!/:?]
6681 | at net.minecraftforge.common.ForgeHooks.modifyLoot(ForgeHooks.java:1320) ~[forge-1.19.2-43.3.5-universal.jar%23674!/:?]
6682 | at net.minecraft.world.level.storage.loot.LootTable.m_230922_(LootTable.java:90) ~[client-1.19.2-20220805.130853-srg.jar%23669!/:?]
6683 | at net.minecraft.world.entity.LivingEntity.m_7625_(LivingEntity.java:1374) ~[client-1.19.2-20220805.130853-srg.jar%23669!/:?]
6684 | at net.minecraft.world.entity.Mob.m_7625_(Mob.java:483) ~[client-1.19.2-20220805.130853-srg.jar%23669!/:?]
6685 | at net.minecraft.world.entity.LivingEntity.m_6668_(LivingEntity.java:1339) ~[client-1.19.2-20220805.130853-srg.jar%23669!/:?]
6686 | at net.minecraft.world.entity.LivingEntity.m_6667_(LivingEntity.java:1298) ~[client-1.19.2-20220805.130853-srg.jar%23669!/:?]
6687 | at net.minecraft.world.entity.LivingEntity.m_6469_(LivingEntity.java:1155) ~[client-1.19.2-20220805.130853-srg.jar%23669!/:?]
6688 | at net.minecraft.world.level.Explosion.m_46061_(Explosion.java:203) ~[client-1.19.2-20220805.130853-srg.jar%23669!/:?]
6689 | at net.minecraft.server.level.ServerLevel.m_7703_(ServerLevel.java:996) ~[client-1.19.2-20220805.130853-srg.jar%23669!/:?]
6690 | at net.minecraft.world.level.Level.m_46511_(Level.java:485) ~[client-1.19.2-20220805.130853-srg.jar%23669!/:?]
6691 | at net.minecraft.world.entity.monster.Creeper.m_32315_(Creeper.java:225) ~[client-1.19.2-20220805.130853-srg.jar%23669!/:?]
6692 | at net.minecraft.world.entity.monster.Creeper.m_8119_(Creeper.java:145) ~[client-1.19.2-20220805.130853-srg.jar%23669!/:?]
6693 | at net.minecraft.server.level.ServerLevel.m_8647_(ServerLevel.java:658) ~[client-1.19.2-20220805.130853-srg.jar%23669!/:?]
6694 | at net.minecraft.world.level.Level.mixinextras$bridge$accept$138(Level.java) ~[client-1.19.2-20220805.130853-srg.jar%23669!/:?]
6695 | at com.bawnorton.neruina.handler.NeruinaTickHandler.safelyTickEntities$notTheCauseOfTickLag(NeruinaTickHandler.java:115) ~[neruina-1.3.0-forge+1.18.2-1.20.1.jar%23572!/:?]
6696 | at net.minecraft.world.level.Level.wrapOperation$ckf000$catchTickingEntities(Level.java:3038) ~[client-1.19.2-20220805.130853-srg.jar%23669!/:?]
6697 | at net.minecraft.world.level.Level.m_46653_(Level.java:457) ~[client-1.19.2-20220805.130853-srg.jar%23669!/:?]
6698 | at net.minecraft.server.level.ServerLevel.m_184063_(ServerLevel.java:323) ~[client-1.19.2-20220805.130853-srg.jar%23669!/:?]
6699 | at net.minecraft.world.level.entity.EntityTickList.m_156910_(EntityTickList.java:54) ~[client-1.19.2-20220805.130853-srg.jar%23669!/:?]
6700 | at net.minecraft.server.level.ServerLevel.m_8793_(ServerLevel.java:303) ~[client-1.19.2-20220805.130853-srg.jar%23669!/:?]
6701 | at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:866) ~[client-1.19.2-20220805.130853-srg.jar%23669!/:?]
6702 | at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:806) ~[client-1.19.2-20220805.130853-srg.jar%23669!/:?]
6703 | at net.minecraft.client.server.IntegratedServer.m_5705_(IntegratedServer.java:84) ~[client-1.19.2-20220805.130853-srg.jar%23669!/:?]
6704 | at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:654) ~[client-1.19.2-20220805.130853-srg.jar%23669!/:?]
6705 | at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:244) ~[client-1.19.2-20220805.130853-srg.jar%23669!/:?]
6706 | at java.lang.Thread.run(Unknown Source) [?:?]

**Comment by Bawnorton** [comment]
This is not a bug with Neruina, from the logs, my best guess is it's caused by a reasonable assumption in apotheosis which may not always be correct when combined with other mods. Please report this bug to them.

**Comment by Krimatoria** [comment]
> Это не ошибка Неруины, судя по журналам, я могу предположить, что она вызвана разумным предположением об апофеозе, которое не всегда может быть правильным в сочетании с другими модами. Пожалуйста, сообщите им об этой ошибке.

Thanks for the quick response. Hopefully I can find a solution along the way.

**Comment by Krimatoria** [comment]
> This is not a bug with Neruina, from the logs, my best guess is it's caused by a reasonable assumption in apotheosis which may not always be correct when combined with other mods. Please report this bug to them.

I wrote to the developer. The problem is solved with the released updated mod Apothic Curios.
