### ISSUE TITLE
[Server thread/WARN]: Neruina Caught Exception + Zombieawareness

### ISSUE THREAD

**Issue by Krimatoria** [Benjamin-Norton/Neruina#44]
https://github.com/Corosauce/ZombieAwareness/issues/119

1. The-Hordes-1.19.2-1.2.2.jar
2. InsaneLib-1.7.5-mc1.19.2.jar
3. EnhancedAI-1.8.5-mc1.19.2.jar
4. Neruina-1.3.0-forge+1.18.2-1.20.1.jar
5. Zombieawareness-1.19.2-1.12.3.jar

**Comment by Bawnorton** [comment]
This is neruina doing what it should do, no need to report it to neruina. The issue is with Zombie awareness.

**Comment by Krimatoria** [comment]
> Неруина делает то, что должна, не нужно сообщать об этом Неруине. Проблема в осведомленности о зомби.

Ok)

**Comment by Krimatoria** [comment]
> Неруина делает то, что должна, не нужно сообщать об этом Неруине. Проблема в осведомленности о зомби.

Yes Neruina is the best mod I've seen so far) Thank you for working on such a cool mod) Really) 🔥
