### ISSUE TITLE
Server crashes on startup

### ISSUE THREAD

**Issue by X-Hellfire-X** [Benjamin-Norton/Neruina#45]
[debug.log](https://github.com/Bawnorton/Neruina/files/14394421/debug.log)

**Comment by Bawnorton** [comment]
Duplicate of #37

**Comment by X-Hellfire-X** [comment]
I am not on forge 47.2.20

**Comment by Bawnorton** [comment]
yes you are
`[cpw.mods.modlauncher.Launcher/MODLAUNCHER]: ModLauncher running: args [--launchTarget, forgeserver, --fml.forgeVersion, 47.2.20, --fml.mcVersion, 1.20.1, --fml.forgeGroup,`
(from your log)

**Comment by X-Hellfire-X** [comment]
but it said it was .18 in the jar install panel
