### ISSUE TITLE
(Request) An Seperate Log File for Neruina Kicks

### ISSUE THREAD

**Issue by Baguetteaus** [Benjamin-Norton/Neruina#46]
Hello, 

I am requesting (if possible), an log file that is separate from the latest.log, and/or other log files, where Neurina can dump the information/reasons for kicks and/or removals of blocks/players/entities. As it can be rather difficult sometimes to catch the error actively in console, or a pain to sift through the log files when it's spammed with a bunch of other things.

I understand if this isn't a thing that is possible or you aren't willing to do so, and appreciate the time you have taken to read this request.

Thanks.

**Comment by Bawnorton** [comment]
The next update has a solution to this by allowing you to copy the crash directly from the message

**Comment by Bawnorton** [comment]
Added in 2.0.0-beta.1
