### ISSUE TITLE
Incompatibility with FishNoStuck (and possibly Fish of Thieves) causing server crash

### ISSUE THREAD

**Issue by Tempest-5ky** [Benjamin-Norton/Neruina#47]
What it says on the tin! A fish from Fish Of Thieves was erroring, though seemingly due to fishnostuck Neruina was unable to remove it.

Fabric 1.20.1
[FishNoStuck](https://modrinth.com/mod/fish-no-stuck) v1.0.1
Neruina v1.3.0
[Fish of Thieves](https://modrinth.com/mod/fish-of-thieves) v0.3.4

Crashlog: https://mclo.gs/ZcEwHbn

I have also reported this issue to FishNoStuck.

**Comment by Bawnorton** [comment]
Fixed in a future version

**Comment by Bawnorton** [comment]
Fixed in 2.0.0-beta.1
