### ISSUE TITLE
Forge 1.18.2 - Neruina will warn of a ticking block entity but not specify where in game or in logs

### ISSUE THREAD

**Issue by FranFkntastic** [Benjamin-Norton/Neruina#48]
![2024-03-05_20 43 04](https://github.com/Bawnorton/Neruina/assets/132225736/239fa03b-5076-4ca4-a0ab-6fcc498b69f0)

No crash so no relevant log to attach. 

Modlist:

- Better village [3.2.0]
- Clumps [8.0.0+17]
- Cyclops Core [1.17.9]
- ImmediatelyFast Reforged [1.18.2-1.1.10]
- Reforgium [1.18.2-1.0.12a]
- YUNG's API [1.18.2-Forge-2.2.9]
- Memory Leak Fix [1.1.2]
- Oculus Particle Fix [1.0]
- Super Saturation [1.18.2-3.0.3]
- FTB Library [1802.3.11-build.177]
- Crabber's Delight [1.1.2]
- Create Diesel Generators [1.18.2-1.2h]
- Create Crafts & Additions [1.18.2-1.0.0]
- Client Tweaks [7.1.0]
- Selene [1.18.2-1.17.14
]
- Death Backup [3.1]
- Create: Design n' Decor [0.1.0]
- EnhancedBlockEntities [1.18.2-0.8.0
]
- Corail Woodcutter [2.3.9]
- Sophisticated Storage [1.18.2-0.8.55.679]
- Roughly Enough Loot Tables (RELT) [1.18-1.2]
- Clientside OPTIONAL
- Oculus [1.6.4]
- Lootintegrations mod [1.18.2-1.5]
- Terralith [2.2.6]
- Create: Alloyed [1.18.2]
- Connectedness [1.18.2-2.0.1a]
- molten_vents_custom_blocks.json
- Supplementaries [1.18.2-1.5.18]
- Just Hammers [0.1.2+mc1.18.2]
- Distant Horizons [2.0.1-a]
- IntegratedDynamics [1.17.3]
- Architectury [4.11.93]
- Awesome dungeon nether [3.1.1]
- Carry On [1.17.1.12]
- Farmer's Delight [1.18.2-1.2.3]
- Let Me Despawn [1.18-forge-1.0.3]
- Ars Elemental [1.18.2-0.4.9.9]
- Dungeon Crawl [2.3.14]
- Nature's Compass [1.18.2-1.9.7-forge]
- Xaero's World Map [1.37.8]
- Awesome dungeon [3.2.0]
- Knaves' Needs [1.1.5.1+1.18.2]
- Explorer's Compass [1.18.2-1.3.0-forge]
- Just Zoom [1.0.2]
- Effortless Building [1.18-2.40]
- Lucent [1.2.2]
- Create Big Cannons [0.5.3.b-nightly-55e3ae8]
- Fusion [1.1.0]
- Gpu memory leak fix [1.18.2-1.6]
- Spice of Life: Apple Pie Edition [1.18.2-1.0.4]
- Immersive Engineering [1.18.2-8.4.0-161]
- YUNG's Better Ocean Monuments [1.18.2-Forge-1.0.3]
- Rechiseled [1.1.5b]
- Cupboard utilities [1.18.2-1.5]
- Pylons [2.2.0]
- Euphoria Patcher [0.3.0-forge]
- Canary [0.2.9]
- Fixed Anvil Repair Cost [3.2]
- YUNG's Better Witch Huts [1.18.2-Forge-1.0.1]
- Archer's Paradox [3.2.1]
- Create Ore Excavation [1.1.1]
- Better Compatibility Checker [1.1.21-build.48+mc1.18.2]
- Create Enchantment Industry [1.2.7.e]
- FTB Ultimine [1802.3.4-build.93]
- Toggle Enchantments [1.0]
- AttributeFix [14.0.2]
- REI Plugin Compatibilities [8.0.89]
- CoFH Core [9.2.3]
- Awesome dungeon edition ocean [3.2.0]
- kotlinforforge-3.12.0-all
- ConnectedTexturesMod [1.18.2-1.1.5+5]
- betterfpsdist mod [1.18.2-1.5]
- koremods-modlauncher-0.4.11
- Pam's HarvestCraft 2 - Food Extended [1.0]
- TexTrue's Embeddium Options [0.1.1+mc1.18.2]
- CC: Tweaked [1.101.3]
- Embeddium [0.2.17+mc1.18.2]
- Simply Swords [1.40-1.18.2]
- Tectonic [1.1.10a]
- Example Mod [1.18.2-2.4]
- YUNG's Better Desert Temples [1.18.2-Forge-1.3.1]
- Xaero's Minimap [23.9.7]
- Curious Elytra [1.18.1-5.0.1.0]
- MaFgLib [0.1.9-mc1.18.2]
- Placebo [6.6.7]
- Enigmatic Legacy [2.25.0]
- FTB Chunks [1802.3.17-build.265]
- Rechiseled: Create [1.0.2]
- No Unused Chunks [1.3]
- Dynamic FPS [3.4.2]
- AppleSkin [2.5.1+mc1.18.2]
- Moog's Voyager Structures [3.0.6]
- Somnia Awoken [1.18.2-3.0.105]
- CommonCapabilities [2.9.1]
- Molten Vents [2.0.6]
- YUNG's Better Nether Fortresses [1.18.2-Forge-1.0.0]
- Separated Leaves [2.3.0]
- Ars Creo [2.2.0]
- FTB Teams [1802.2.11-build.107]
- Configured [2.0.1]
- Cristel Lib [1.0.0]
- Collective [7.7]
- default_mods_update9_Fran_Behaviour_2.rar
- Lio's Overhauled Villages [0.0.2-1.18.2-1.20.4-Universal]
- Create Slice & Dice [1.3.2]
- Ars Instrumentum [2.4.1]
- Searchables [1.0.1]
- Harvest with ease [8.0.1.0]
- spark [1.9.11]
- Enchanted Book Redesign [1.18.2-1]
- Curios API [1.18.2-5.0.9.2]
- e4mc [4.0.1]
- Mouse Tweaks [2.22]
- Smoothchunk mod [1.18.2-1.9]
- Roughly Enough Items (REI) [8.3.681]
- Create: Steam 'n Rails [1.4.8+forge-mc1.18.2-build.23]
- Nullscape [1.1.4]
- Apotheosis [5.8.1]
- ReAuth [4.0.7]
- Additional Entity Attributes [1.18.2-1.4.1.4]
- Towns and Towers [1.10.0.1]
- Trade Cycling [1.18.2-1.0.2]
- Additional Structures [3.1.1]
- FPS optimizer [1.0.0]
- Not Enough Crashes [4.2.0+1.18.2]
- Controlling [9.0+23]
- Player Animator [1.0.2+1.18]
- Tinker Leveling [0.4.0]
- Reliquary [1.18.2-2.0.19.1161]
- Tinkers' Integrations and Tweaks [1.18.2-2.0.18.1]
- Yeetus Experimentus [1.0.1-build.4+mc1.18.2]
- Saturn [0.1.3]
- Caelus API [1.18.1-3.0.0.2]
- Jade [5.3.1]
- EnchantmentDescriptions [10.0.12]
- Tinkers' Katanas [1.0.3]
- Puzzles Lib [3.5.8]
- Curious Armor Stands [1.18.1-4.0.1]
- Tweakerge [0.1.2-mc1.18.2]
- Patchouli [1.18.2-71.1]
- Rubidium Extra [0.4.18+mc1.18.2-build.86]
- CookingForBlockheads [12.2.0]
- Pam's HarvestCraft 2 - Crops [1.0.6]
- Wall-Jump! [1.18.1-1.3.7]
- EntityCulling [1.6.1]
- Fastload-Reforged [3.4.0]
- SuperMartijn642's Core Lib [1.1.16]
- Konkrete [1.6.1]
- Journeymap [5.9.7]
- Bookshelf [13.3.56]
- Extreme Sound Muffler [3.31_forge-1.18.2]
- Corpse [1.18.2-1.0.1]
- Universal Bone Meal [3.1.0]
- Lightspeed [1.18.2-1.1.0]
- Polymorph [1.18.2-0.49]
- Scannable [1.7.6]
- Tinkers' Construct [3.6.4.113]
- Storage Drawers [10.2.1]
- Not Enough Recipe Book [0.3]
- Blood Magic [1.18.2-3.2.6-41]
- Sophisticated Backpacks [1.18.2-3.19.5.990]
- Observable [2.2.3]
- Inventory Profiles Next [1.10.9]
- Ars Omega [1.18.2-2.7.4]
- Ferrite Core [4.2.2]
- It Shall Not Tick [1.0.22-build.34]
- Sophisticated Core [1.18.2-0.5.111.526]
- Easy Anvils [3.0.0]
- Mantle [1.9.45]
- Relics [0.4.1.8]
- Create: Interactive [1.0.0-beta.3]
- Oculus Flywheel Compat [1.18.2-0.2.1]
- SuperMartijn642's Config Library [1.1.8]
- Create: Interiors [0.5.2]
- Json Things [0.4.15]
- Chunky [1.2.164]
- Balm [3.2.6]
- Tinkers' Rapier [1.1.5-1.18.2]
- ArmorPoints++ [1.18.2-3.1.0]
- Pam's HarvestCraft 2 - Food Core [1.0.1]
- Pam's HarvestCraft 2 - Trees [1.0.1]
- WITS [1.1.0+1.18.2-forge]
- Connectivity Mod [1.18.2-3.2]
- Ensorcellation [3.2.2]
- VS Eureka Mod [1.4.0-beta.1]
- When Dungeons Arise [2.1.52-1.18.2]
- Ars Nouveau [2.9.0]
- Library ferret [4.0.0]
- Lootr [0.3.25.62]
- MmmMmmMmmMmm [1.18-1.5.2]
- Valkyrien Skies 2 [2.1.1-beta.5]
- Copies & Cats [1.0]
- Create [0.5.1.f]
- libIPN [4.0.1]
- LazyDFU [0.1.3]
- Refined Storage [1.10.6]
- ModernFix [5.13.0+mc1.18.2]
- Starlight [1.0.2+forge.83663de]
- Better Combat [1.6.2+1.18.2]
- Create Renewable Ores [1]
- CosmeticArmorReworked [1.18.2-v2a]

**Comment by Bawnorton** [comment]
Some other mod is breaking translations, I can't fix this.

**Comment by FranFkntastic** [comment]
Any tips to finding which? Not going to ask you to scrawl through the whole modlist but it could really be any of them with my limited knowledge of how they're made...

**Comment by Bawnorton** [comment]
Not really, the next version of neruina will provide more actions and control which will allow you to teleport to the location where the ticking entity is caught. This is planned to be released when 1.20.5 is released (I am still maintaining support for 1.18.2).
In the meantime you can have a look at your logs to see what Neruina caught which would give you an idea
