### ISSUE TITLE
Crashes occurring when used alongside ISWYDT mod

### ISSUE THREAD

**Issue by Killercrab432** [Benjamin-Norton/Neruina#49]
Crashes occur decently often when used alongside ISWYDT https://www.curseforge.com/minecraft/mc-mods/i-see-what-you-did-there 

included are some crash logs below and the issue opened up on the other mod github

https://pastebin.com/JyDHmLBB

https://pastebin.com/1dQmxuGZ

https://github.com/Khajiitos/ISWYDT/issues/3

**Comment by Bawnorton** [comment]
This is caused by ISWYDT, I'll state why there.
