### ISSUE TITLE
Hello, I am a staff member at DarkRPG and we are wondering if you have any insights in to this problem.

### ISSUE THREAD

**Issue by KonekoNyarla** [Benjamin-Norton/Neruina#5]
Not sure if this is even related to you but we are hoping that you may know something about this but we are getting a bug where after a while items that link together for example: chests, fences and walls don't link or the link is broken.

We are unable to replicate this bug as it happens randomly and we were hoping to see if you maybe had someone who has reported the same thing happening or something of this kind.

here is an image of what I am referring to: https://cdn.discordapp.com/attachments/1077294784877695017/1126606768835940403/image.png

**Comment by Bawnorton** [comment]
Hi, Neruina has nothing to do with this. Neruina only affects ticking and that does not impact anything related to block models
