### ISSUE TITLE
Neruina performance

### ISSUE THREAD

**Issue by zoqin** [Benjamin-Norton/Neruina#50]
Hello, i'm trying to build an expensive and ambitious modpack with a lot of entity and asset while archiving a smooth experience

Neruina very rarely find something to kill but in the otherhand it's the mod that use the most of my ticks time

I guess it's inevitable to sacrifice part of my ressource to Neruina 

But i'm wondering if it was possible to have some way to configure how much ressource we were willing to sacrifice

Or if my vision of the issue I encounter is totally wrong and need to learn some specific things on Neruina/Minecraft modding 

Thanks for your time and consideration

**Comment by Bawnorton** [comment]
Because Neruina wraps all the tick methods Spark and other profilers will assume the entire content (i.e. all the entity and block entity ticks) belong to Neruina, which is not the case, they belong to the vanilla game. You will need to expand the high % section to see what is causing the lag

**Comment by zoqin** [comment]
Thanks so much for your valuable knowledge

I will figure it out on myself moving forward 

Have a nice day
