### ISSUE TITLE
Friends&Foes server crash

### ISSUE THREAD

**Issue by Faboslav** [Benjamin-Norton/Neruina#52]
Do you have any idea, what can be the cause based on this issue? https://github.com/Faboslav/friends-and-foes/issues/191
Is `Canary Class Analysis` thing calling my classes on bad environment?

**Comment by Bawnorton** [comment]
I don't believe you're at fault for this. Looking over the report, log, source of your mod and canary it looks like some other mod overrides `Entity#collidesWith` and is attempting to use `PlayerInfo` somewhere in it without checking the side. At least that's my best guess.

**Comment by Bawnorton** [comment]
This is likely a symptom of all 3 mods being present at the same time.

**Comment by Bawnorton** [comment]
Since this is not an issue with neruina itself as it handled it in an expected manner, I'm closing this
