### ISSUE TITLE
[Issue] Neruina taking noticeable amounts of tick time process entities

### ISSUE THREAD

**Issue by User4716** [Benjamin-Norton/Neruina#53]
I don't know why Neruina lags my client this much. I know it has to check for erroring entities all the time and it can and will cause lag, but I'm not going to just give out 14% of my client's performance to just prevent a crash which will probably not even happen often.

I'll test an alternative erroring entity removal mod and see how much that lags my game. If this lag is not normal then please let me know, because I can't tell if a mod is conflicting with Neruina / causing extra entity checks for Neruina, or if the entity checking is truly this intensive.

https://spark.lucko.me/iX6v4HpZi1

![image](https://github.com/Bawnorton/Neruina/assets/97033682/12490e54-955c-4653-80ec-dd26b077d0ae)
![image](https://github.com/Bawnorton/Neruina/assets/97033682/68d2b243-145d-4d6a-869b-2013faccc3e0)
![image](https://github.com/Bawnorton/Neruina/assets/97033682/12e31a07-3d65-4ce8-be49-8150e561f5a8)

# Mods used:

> 	- advanced_enchantments 1.0.2
> 	- advancednetherite 2.0.3
> 	- advancementscreenshot 4.7
> 	- alexscaves 1.1.4
> 	- ambientsounds 5.3.9
> 	- appleskin 2.5.1+mc1.20.1
> 	- architectury 9.2.14
> 	- ars_nouveau 4.9.0
> 	- axesareweapons 1.7.3
> 	- azurelib 2.0.20
> 	- balm 7.2.2
> 	- beekeeperhut 2.0.0
> 	- better_beacons 2.0.0
> 	- better_totem_of_undying 2.0.1
> 	- betterarcheology 1.1.7-1.20.1
> 	- bettercombat 1.8.0+1.20.1
> 	- betterdeserttemples 1.20-Forge-3.0.3
> 	- betterdungeons 1.20-Forge-4.0.3
> 	- betterfortresses 1.20-Forge-2.0.6
> 	- betterjungletemples 1.20-Forge-2.0.4
> 	- bettermineshafts 1.20-Forge-4.0.4
> 	- betteroceanmonuments 1.20-Forge-3.0.4
> 	- betterstrongholds 1.20-Forge-4.0.3
> 	- bettertridents 8.0.1
> 	- betterwitchhuts 1.20-Forge-3.0.3
> 	- boatbreakfix 1.0.1
> 	- boatiview 0.0.5
> 	- bountiful 6.0.3+1.20.1
> 	- brb 1.10.0+1.20.0-1
> 	- caelus 3.1.0+1.20
> 	- canary 0.3.3
> 	- catalogue 1.8.0
> 	- cell 2.1
> 	- cerbons_api 1.1.0
> 	- chat_heads 0.10.32
> 	- chunksending 1.20.1-2.8
> 	- citadel 2.5.4
> 	- cloth_config 11.1.118
> 	- collective 7.40
> 	- combatroll 1.3.1+1.20.1
> 	- configured 2.2.3
> 	- connectedglass 1.1.11
> 	- controlling 12.0.2
> 	- corgilib 4.0.1.1
> 	- craterlib 1.1.1
> 	- creativecore 2.11.25
> 	- cupboard 1.20.1-2.6
> 	- curios 5.7.2+1.20.1
> 	- deathfinder 8.0.1
> 	- deeperdarker 1.2.1
> 	- dogslie 1.2.0
> 	- dynamic_fps 3.4.2
> 	- dynamiclights 1.7.1+mod
> 	- dynmus 2.3.2+1.20
> 	- easyanvils 8.0.2
> 	- easymagic 8.0.1
> 	- embeddium 0.3.9+mc1.20.1
> 	- embeddium_extra 0.5.4.2+mc1.20.1-build.118
> 	- enchantingcommands 3.3
> 	- end_respawn_anchor 1.20.1-1.0.0
> 	- endrem 5.2.3-R-1.20.1
> 	- enhancedai 2.0.5
> 	- enhancedcelestials 5.0.0.2
> 	- entity_model_features 1.2.3
> 	- entity_texture_features 5.2.1
> 	- entityculling 1.6.2
> 	- explorify 1.3.0-mc1.20
> 	- extra_enchantments 1.7.2
> 	- fallingleaves 2.1.0
> 	- fastback 0.15.2+1.20.1-prerelease
> 	- fastipping 1.0.1
> 	- ferritecore 6.0.1
> 	- foodeffecttooltips 1.0.0
> 	- forge 47.1.102
> 	- freecam 1.2.1+1.20
> 	- friendsandfoes 2.0.10
> 	- fullbrightnesstoggle 4.0
> 	- fullstackwatchdog 1.0.1+1.19.2-forge
> 	- fusion 1.1.1
> 	- geckoanimfix 1.0.0
> 	- geckolib 4.4.4
> 	- geophilic 2.2.0-mc1.20u1.20.2
> 	- goated 1.20-1.3.4
> 	- graveyard 3.1
> 	- hopour 1.1.4
> 	- immediatelyfast 1.2.10+1.20.4
> 	- immersive_weathering 1.20.1-2.0.1
> 	- infinity_cave 0.4
> 	- insanelib 1.12.1
> 	- inventoryessentials 8.2.3
> 	- irons_spellbooks 1.20.1-3.1.0
> 	- justzoom 1.0.2
> 	- kambrik 6.1.1+1.20.1
> 	- kiwi 11.5.5
> 	- konkrete 1.8.0
> 	- kotlinforforge 4.10.0
> 	- leavemybarsalone 8.0.0
> 	- lmft 1.0.4+1.20.1
> 	- majruszlibrary 7.0.5
> 	- majruszsenchantments 1.10.7
> 	- maptooltip 3.0.1
> 	- memoryleakfix 1.1.5
> 	- minecraft 1.20.1
> 	- mixinextras 0.2.0
> 	- mixinsquared 0.1.1
> 	- modelfix 1.15
> 	- modernfix 5.15.0+mc1.20.1
> 	- moonlight 1.20-2.11.9
> 	- mousekeyinventoryfix 1.2.0
> 	- mousetweaks 2.25
> 	- mr_deeper_dark 2.2.1
> 	- mr_dungeons_andtaverns 3.0.3
> 	- mr_dungeons_andtavernspillageroutpostrework 1.1
> 	- mr_limesplatus_ending 1-v1.1.0c
> 	- mr_stellarity 2.0d
> 	- mr_villager_transportation 1.2
> 	- necronomicon 1.4.2
> 	- neruina 1.3.0
> 	- no_telemetry 1.8.0
> 	- nochatreports 1.20.1-v2.2.2
> 	- notenoughanimations 1.7.1
> 	- notenoughcrashes 4.4.7+1.20.1
> 	- nyctophobia 1.6
> 	- nyfsspiders 2.1.1
> 	- oculus 1.6.15a
> 	- packetfixer 1.2.8
> 	- plasmovoice 2.0.8
> 	- playeranimator 1.0.2-rc1+1.20
> 	- playerrevive 2.0.24
> 	- puzzlesaccessapi 8.0.7
> 	- puzzleslib 8.1.18
> 	- pv_addon_soundphysics 1.0.1
> 	- rare_ice 0.0NONE
> 	- rrls 3.2.0-1.20.1-forge
> 	- rubidium 0.7.1
> 	- rw_deepdark 3
> 	- screenshot_viewer 1.2.1-forge-mc1.20.1
> 	- screenshotclipboard 1.0.9
> 	- sculk_expansion_mr 1.3.0
> 	- sculkhornid 1.4.5
> 	- searchables 1.0.2
> 	- sereneseasons 9.0.0.46
> 	- simplerpc 3.2.4
> 	- simplyswords 1.54.0-1.20.1
> 	- sit 1.3.4
> 	- smallships 2.0.0-b1.1
> 	- smarterfarmers 1.20-1.8.3
> 	- smoothboot 0.0.4
> 	- smoothchunk 1.20.1-3.6
> 	- snifferplus 0.2.0
> 	- snowrealmagic 10.4.1
> 	- soulfired 3.2.0.1-final
> 	- sound_physics_remastered 1.20.1-1.3.0
> 	- spark 1.10.53
> 	- spellbound_weapons_mr 4.0.5l
> 	- spells_and_shields 1.20.1-2.16.0
> 	- starlight 1.1.2+forge.1cda73c
> 	- structureessentials 1.20.1-3.3
> 	- suggestion_tweaker 1.20-1.5.1
> 	- supermartijn642corelib 1.1.12a
> 	- terrablender 3.0.1.4
> 	- tlc 1.0.2
> 	- unsafe_world_random_access_detector 1.1.0+forge
> 	- variantsandventures 1.0.1
> 	- waterdripsound 0.3.2
> 	- waveycapes 1.4.4
> 	- whats_that_slot 1.3.4
> 	- witherstormmod 4.0.1.1
> 	- worldedit 7.2.15+6463-5ca4dff
> 	- yungsapi 1.20-Forge-4.0.4

**Comment by Bawnorton** [comment]
Neruina doesn't cause any lag and you can see it in the spark report by the self-time metrics. The usage between Neruina method calls and vanillas tick calls is less than 0.01%.

Neruina wraps vanilla tick calls, it doesn't check every tick, it just catches any errors thrown during the ticking process. I literally called the method "notTheCauseOfTickLag" and put a notice on the mod page.
