### ISSUE TITLE
[feature]: Show Erroring Entity name and cordinates!

### ISSUE THREAD

**Issue by Merith-TK** [Benjamin-Norton/Neruina#55]
Just a simple update to the error message where it gets the ID of what it is, and its coords for entities/blocks, 
would be really nice for admins

**Comment by Bawnorton** [comment]
Already planned and implemented in a future release, just waiting for 1.20.5 to release so I can target a stable version. https://github.com/Bawnorton/Neruina/blob/stonecutter/CHANGELOG.md

**Comment by Merith-TK** [comment]
Was hoping it could be released for older versions as well, as a decent amount of modpacks still target 1.20.1 (like mine for example)

**Comment by Bawnorton** [comment]
It will still maintain support for all versions

**Comment by Bawnorton** [comment]
Added in 2.0.0-beta.1
