### ISSUE TITLE
Neruina 2.0 State

### ISSUE THREAD

**Issue by Bawnorton** [Benjamin-Norton/Neruina#56]
Most of the work for the new system is done, see the [changelog](https://github.com/Bawnorton/Neruina/blob/stonecutter/CHANGELOG.md)

This version will support 1.18.2-1.20.5 fabric, forge and neoforge and I am to release it when 1.20.5 releases. I am currently unavailable to continue work as of right now as I am a college student and it's exam season, this means that it'll likely release around the start of May provided 1.20.5 is out by then. 

This version fixes #37, #22 and #47,  and introduces features similar to the ones mentioned in #55 and #46

**Comment by creaper3** [comment]
ty! can't wait for it to come out so I can put it on my server again (atm9).

**Comment by 8MiYile** [comment]
Congrats, I can't wait to use this mod!

**Comment by Bawnorton** [comment]
Waiting on Arch to support 1.20.6 neo/forge

**Comment by Bawnorton** [comment]
2.0 is released. Testing welcome.
