### ISSUE TITLE
Fixing Ticking Entity

### ISSUE THREAD

**Issue by iLegendaryTyler** [Benjamin-Norton/Neruina#57]
When I try to join my friends server I get kicked for ticking entity.

This is the error code

Neruina Caught Exception
java.lang.NullPointerException: Cannot read field "use_vanilla_magic_damage_type" because "net.spell_power.SpellPowerMod.attributesConfig.value" is null

When I go into the attributes file in the spell_power folder this is what I see

{
"use_vanilla_magic_damage_type": true,
"base_spell_critical_chance_percentage": 5.0,
"base_spell_critical_damage_percentage": 50.0
}

So I was wondering why Neruina was kicking me from the server?

**Comment by Bawnorton** [comment]
Report to spell power and include your full log. This is Neruina functioning as expected so I'm closing this
