### ISSUE TITLE
Crash on Startup, Error Code 1

### ISSUE THREAD

**Issue by zeven1707** [Benjamin-Norton/Neruina#58]
https://pastebin.com/3CYkjs3r
Log provided, however it has been cut off.

MC Version 1.20.1
Mod Version neruina-1.3.0-forge+1.18.2-1.20.1

Without mod, no issue, however after installing the mod. Game crashes with no crash log.

**Comment by Bawnorton** [comment]
Can't resolve this without a complete log or crash report as I don't know what is breaking

**Comment by LunarDev-git** [comment]
Allow me, It always crashing in loading bootstrap resources. 

I'm on Forge 47.2.30
with neruina-1.3.0-forge+1.18.2-1.20.1.jar
[latest.log](https://github.com/Bawnorton/Neruina/files/15179268/latest.log)

This is with just neruina.


Take this as purely optional but: 
I have another pack that's indev (with 298 mods) I was testing which may lead to something more but it kept crashing at this line 

"Redirecting net/minecraft/world/entity/ai/attributes/AttributeModifier$Operation"

**Comment by Bawnorton** [comment]
#37

**Comment by LunarDev-git** [comment]
F- Sorry!
