### ISSUE TITLE
Kills all mobs

### ISSUE THREAD

**Issue by blackstormlab** [Benjamin-Norton/Neruina#59]
allright so it doesn't actually kill every single mob but it does kill like a massive amount of them even just passive mobs in my farm.

and i think its safe to say thats not intended behaviour.

let me know how i could help assist in finding the issue if i need to pull logs from anywhere...

**Comment by Bawnorton** [comment]
If lots of entities are being killed, something is seriously wrong, share your logs and I'll lyk which mod, if any is breaking.
https://docs.fabricmc.net/players/troubleshooting/uploading-logs

**Comment by blackstormlab** [comment]
[2024-04-23-4.log](https://github.com/Bawnorton/Neruina/files/15088201/2024-04-23-4.log)

**Comment by blackstormlab** [comment]
that should be the log right before i removed it since it kept killing too many things.

i see reliquary in the errors but without neruina everything is running fine.

**Comment by Bawnorton** [comment]
`reliquary` is definitely failing, what's odd is the stack trace for the later errors, the ones that are killing everything is that they are empty.. 😕.

Anyway, this behaviour is changed in 2.x which will fix this, and that will release soon #56

**Comment by blackstormlab** [comment]
but i was right that this was unintended behaviour right?

so nothing that i can do but uninstall and wait for 2.0?

because the promise of this mod sounds really interesting.

**Comment by Bawnorton** [comment]
No, this was intended, Neruina is designed to prioritise your world over its content, the update will change the killing to suspension and there is a threshold of the number of entities suspended in a short time will generate a comprehensive crash report
