### ISSUE TITLE
[1.20.1] crash when mounting players when using mods to do so.

### ISSUE THREAD

**Issue by netcore10** [Benjamin-Norton/Neruina#61]
seems it doesn't expect, or know how to handle player's mounting players, so crashes.
[crash-2024-04-29_19.54.37-client.txt](https://github.com/Bawnorton/Neruina/files/15156129/crash-2024-04-29_19.54.37-client.txt)
[crash-2024-04-29_18.54.23-client.txt](https://github.com/Bawnorton/Neruina/files/15156130/crash-2024-04-29_18.54.23-client.txt)

Specifically "com.bawnorton.neruina.exception.DoNotHandleException" showed up quite a bit. We were testing origins mounting.

**Comment by Bawnorton** [comment]
You have FSit on your client. It's a server-side mod. It should handle client installation gracefully but it doesn't so it crashes.
