### ISSUE TITLE
Create Contraptions do not drop items when killed

### ISSUE THREAD

**Issue by SabrCat** [Benjamin-Norton/Neruina#62]
As the title says, I just tested the mod with create mod 0.5.1d 1.20.1, which has a known crash when a deployer kills an entity. The block entity ticking stop works perfectly. However, when the deployer is put on a contraption and errors, the entire contraption gets deleted and does not drop any inventory content it had, potentially deleting thousands of items e.g. a mining drill contraption could contain and also the many blocks it was made out of. 
It at least dropping it's inventory would be nice, though just stopping entity ticking in some way that allows the contraption to be recovered would be even better, if such a thing is possible.

**Comment by Bawnorton** [comment]
See #56. This moves from killing to suspension which would fix this as the inventory should still be accessible (in theory). I'm almost done with it, just doing final testing because there's a lot that needs to go right.

**Comment by Bawnorton** [comment]
Fixed in 2.0.0-beta.1

**Comment by SabrCat** [comment]
I tested it with the known deployer crash, and it works great! The entities not getting killed is nice, and resume ticking is a great functionality that is very useful, as the deployer crash only happened once, but can resume fine after. This completely mitigates the crash.  
Quick question, if I set the broadcast to everyone to notify players, can I still restrict clicking the buttons (like resume) to operators?

**Comment by Bawnorton** [comment]
Resume and kill require permission level 2 (normal users have 1, operators have 4), the other actions don't require any perms

**Comment by SabrCat** [comment]
sounds good, and I assume vanilla TP permissions will work for whoever has them too. I have luckperms, so that should work then. Excellent. Thanks again for the update, that means I can (relatively) safely leave the mod default enabled and cut down on crashes.
