### ISSUE TITLE
Neruina ticking non existant armor stands causing lag?

### ISSUE THREAD

**Issue by CorneliusCornbread** [Benjamin-Norton/Neruina#67]
So I'm running into an issue with my server where certain chunks being loaded will lag the server. It's not create related unlike what I might think, I can pinpoint the lag to one spot based on client lag (it lags the client too interestingly enough). I've tracked the issue down to this mod, least as far as I can tell. I took a spark profile and walked around my world, the TPS drops are when I enter the problematic chunks, no other player base is causing lag like this.

Server profile:
https://spark.lucko.me/Ixb1TGCddE

It seems like the game is ticking invisible armor stands? But attempting to kill armor stands in a 30 block radius of the pinpointed problem area just leads to the game reporting that "no entities were found"

I'll do some more testing tomorrow, see if I can uninstall neruina and see if that fixes it.

Forge 47.2.32
Minecraft 1.20.1
openjdk 17

Here's also the client profile:
https://spark.lucko.me/zeZuo7gux5

**Comment by Bawnorton** [comment]
#53 Profilers do not understand this mod an incorrectly attribute it as the source of lag.
