### ISSUE TITLE
Neruina and Mobtimizations

### ISSUE THREAD

**Issue by chmonyasik** [Benjamin-Norton/Neruina#68]
Forge: 47.2.30
Minecraft: 1.20.1

Know that I don't have to rely on spark, so the main question is compatibility of Mobtimizations and Neruina, they don't break each other and can work together in peace? Any thoughts on that? Just want to get your opinion on this

![Screenshot_10](https://github.com/Bawnorton/Neruina/assets/94359925/b8cf0838-763f-4394-852f-8fea15bc2c8b)

**Comment by Bawnorton** [comment]
#53 Profilers do not understand this mod an incorrectly attribute it as the source of lag.

**Comment by chmonyasik** [comment]
I know, I'm interested in your opinon about mobtimizations, spark just to show that there are maybe some same implementations

**Comment by Bawnorton** [comment]
Never heard of it
