### ISSUE TITLE
Some client crash by one of my server users 1.19.2 Forge

### ISSUE THREAD

**Issue by BlackAures1** [Benjamin-Norton/Neruina#69]
Full crash report: [crash-2024-05-16_09.57.10-client.txt](https://github.com/Bawnorton/Neruina/files/15358377/crash-2024-05-16_09.57.10-client.txt)

`at TRANSFORMER/relics@0.4.7.5/it.hurts.sskirillss.relics.client.hud.abilities.AbilitiesRenderHandler.getAbilityByIndex(AbilitiesRenderHandler.java:345)`

and 

`at TRANSFORMER/neruina@1.3.0/com.bawnorton.neruina.handler.NeruinaTickHandler.handleEntityTicking(NeruinaTickHandler.java:160)`

Just some random crash by one of my server users. Happens rarely, but regularly. Can you suggest a solution to the problem? If it's an old version of your mod, I apologize.

**Comment by Bawnorton** [comment]
Report to relics. Neruina 2.0 handles these better but it won't fix it.

**Comment by BlackAures1** [comment]
Thank you for your reply
