### ISSUE TITLE
Minecraft forge 1.19.2 does not start up with 2.0.0 beta 6

### ISSUE THREAD

**Issue by Rhysindrycal** [Benjamin-Norton/Neruina#70]
Hello,

I had updated neruina from 1.1.0 to 2.0.0 beta 6 and strait away when I clicked play the game wouldn't start. I wasn't sure what was going on when I went through the log because it was flagging a couple of things, so I disabled a ton of mods, but nothing worked. So, I decided to backtrack 2 updates, neruina and immediately fast, since those are the only 2 that I updated that has anything to do with smoothing out the game. Once I backtracked it the game worked without neruina updated and I compared the 2 logs from before and after. 
![Updated neruina](https://github.com/Bawnorton/Neruina/assets/110434155/ac1e6700-33b4-4f07-9c31-439a10b81c31)
![not updated](https://github.com/Bawnorton/Neruina/assets/110434155/d1eb22d5-d3cf-43f9-ab7b-ef0f88ceb82b)

The line:
Error loading class: net/minecraft/world/damagesource/DamageSources (java.lang.ClassNotFoundException: net.minecraft.world.damagesource.DamageSources)

**Comment by Bawnorton** [comment]
forgot 1.19.3 basically re-wrote half the game for some reason

**Comment by Bawnorton** [comment]
Fixed in .8
