### ISSUE TITLE
Minecraft Fabric Dedicated Server 1.19.2 with Neruina 2.0.0 beta 7 couldn`t start 

### ISSUE THREAD

**Issue by IruNil6** [Benjamin-Norton/Neruina#71]
Hi, I tried to run the server without any mods except Neruina on a dedicated fabric server, but I got too many exceptions and the server shut down

Here is my [log](https://github.com/Bawnorton/Neruina/files/15384189/latest.log) file

**Comment by Bawnorton** [comment]
somehow my build corrupted itself mid-publish. New one on me. I re-compiled and published as .8
