### ISSUE TITLE
Latest release (beta 7) server log

### ISSUE THREAD

**Issue by sternschnaube** [Benjamin-Norton/Neruina#72]
[Server thread/ERROR]: Invalid path in mod resource-pack neruina: neruina:neruina/auto_report 3.json, ignoring
[Server thread/ERROR]: Invalid path in mod resource-pack neruina: neruina:neruina/auto_report 2.json, ignoring
[Server thread/ERROR]: Invalid path in mod resource-pack neruina: neruina:storage/a 3.json, ignoring
[Server thread/ERROR]: Invalid path in mod resource-pack neruina: neruina:storage/a 2.json, ignoring

**Comment by Bawnorton** [comment]
somehow my build corrupted itself mid-publish. New one on me. I re-compiled and published as .8
