### ISSUE TITLE
Minecraft Fabric Dedicated Server 1.19.2 with Neruina 2.0.0 beta 8 couldn`t start

### ISSUE THREAD

**Issue by IruNil6** [Benjamin-Norton/Neruina#73]
Same problem like in #71

I don`t now what is going on, but u can check my log file again)

[latest.log](https://github.com/Bawnorton/Neruina/files/15391992/latest.log)

**Comment by Bawnorton** [comment]
found the issue, can you try .9
this is why we have betas 😅

**Comment by irunil-ru** [comment]
Now it`s crash the server)
It's okay, I understand what else is in beta

[crash-2024-05-21_19.21.57-server.txt](https://github.com/Bawnorton/Neruina/files/15392674/crash-2024-05-21_19.21.57-server.txt)

**Comment by Bawnorton** [comment]
looks like I'll need to bundle a newer version of gson as it looks like 1.19.2 uses quite an old version

**Comment by Bawnorton** [comment]
Fixed in .10. It'll be available shortly

**Comment by irunil-ru** [comment]
Yep it works without any mods, buuut i`ll check it with other mods later

**Comment by brisingraerowing** [comment]
This issue also affects the Forge version, FWIW.
