### ISSUE TITLE
Too many ticking exceptions in a short period of time

### ISSUE THREAD

**Issue by mpustovoi** [Benjamin-Norton/Neruina#74]
I created a test world to test shaders.
Entity tick errors were constantly appearing in the chat, mostly zombies and witches, then husks. In the end, the game crashed.
This is my first experience using `Neruina` after the 2.0 update.
[Crash-report and latest.log](https://gist.github.com/mpustovoi/2b353d000f13545263d25d5509b4fee5) (I'm sorry that some of the messages are in Russian)

**Comment by mpustovoi** [comment]
Is my world corrupted or is it some kind of incompatibility?
I don't think I have mods that make changes to the AI of caught errorring vanilla mobs.

**Comment by Bawnorton** [comment]
See https://github.com/Bawnorton/Neruina/wiki/Too-Many-Ticking-Exceptions this is intended behaviour 

let me despawn is breaking.. badly

**Comment by mpustovoi** [comment]
I know that `Too many ticking exceptions` is intentional. I looked that it could be disabled in config, but I don't think it's an option for me.
So I guess I should create an issue in `Let Me Despawn` repo.

**Comment by Bawnorton** [comment]
Yes
