### ISSUE TITLE
Crash when loading any world (Forge 1.19.2)

### ISSUE THREAD

**Issue by Coremn-JackC** [Benjamin-Norton/Neruina#75]
Hello.

Whenever I launch the game and open a world, the game crashes to desktop.

Crash Report:
[crash-2024-05-24_12.33.29-server.txt](https://github.com/Bawnorton/Neruina/files/15441560/crash-2024-05-24_12.33.29-server.txt)

I believe that this error may be due to a formatting error somewhere within this file: https://github.com/Bawnorton/Neruina/blame/stonecutter/src/main/java/com/bawnorton/neruina/report/AutoReportConfig.java

My current Minecraft Forge Version:
1.19.2-43.3.5

Thank you :)

**Comment by Bawnorton** [comment]
Update to beta 10
