### ISSUE TITLE
[1.18.2] Mixin Failure

### ISSUE THREAD

**Issue by Secretname2009** [Benjamin-Norton/Neruina#8]
Im reporting a crash that prevents Minecraft from starting at all.
I may provide more information if neccesary but below is the basics.
Minecraft 1.18.2
Forge 40.2.10
Neruina 1.1.0
No See, No Tick 1.0.0
And 299 Other mods.
[latest.log](https://github.com/Benjamin-Norton/Neruina/files/12239347/latest.log)

**Comment by Bawnorton** [comment]
Fixed in [1.1.1+1.18.2](https://github.com/Benjamin-Norton/Neruina/releases/edit/1.1.1)
