### ISSUE TITLE
Whether to consider support for 1.16.5 forge？

### ISSUE THREAD

**Issue by ZHI-CCC** [Benjamin-Norton/Neruina#80]
1.16.5 is the version with the most mods and also the version with the most bugs
We really need this version of the mod to solve the bugs we encountered in multiple mods
Your change will elevate 1.16.5 to a higher level

**Comment by Bawnorton** [comment]
> 1.16.5 is the version with the most mods

not even close, nor does it have the most users.

I won't be downgrading below 1.18.2, which I'll likely be dropping soon too, because the increase in development time does not make sense as there is minimal demand for it and I do this in my spare time.
