### ISSUE TITLE
READ READ READ Neruina causing tps lag

### ISSUE THREAD

**Issue by StormbringerGTX** [Benjamin-Norton/Neruina#83]
I do have a large number of mods that add new mobs and a lot of villagers in one spot, so I am guessing this is causing Nerunia to work overtime. In the event something else is happening I figured I'd bring this to your attention, here is my Spark profile.

https://spark.lucko.me/iADhVAKnjH

**Comment by Bawnorton** [comment]
neruina doesn't cause lag, it wraps minecrafts tick calls and profilers don't understand that, you can even see it in the profiler linked. It just takes a bit more than reading the surface number.

**Comment by StormbringerGTX** [comment]
Thanks for the insight!

**Comment by mateus3c** [comment]
Actually I was having HUGE TPS lag on my world and I remembered you saying that It wasn't Neruina but after trying everything to fix besides removing Neruina, I finally removed it and the lag was magically gone.
When I was playing with Neruina items would not drop, mobs would not move, chunks would freeze and not load, I couldn't open my inventory and nothing I typed on the chat was really sent, after removing Neruina all that was fixed (I did all my tests recreating the same world seed and making the exact same movement)

**Comment by Bawnorton** [comment]
Send spark report with neruina present

**Comment by mateus3c** [comment]
[https://spark.lucko.me/ZExyHGlo9b](https://spark.lucko.me/ZExyHGlo9b)

**Comment by Bawnorton** [comment]
<img width="726" alt="Screenshot 2024-09-19 at 3 34 32 PM" src="https://github.com/user-attachments/assets/a7cbd6c2-9949-46f2-ab38-3996bd435a26">

Lag caused by a powered spawner accessing a chunk incorrectly

**Comment by mateus3c** [comment]
but I don't understand why removing neruina fixed the lag?

**Comment by Bawnorton** [comment]
Send a spark report with neruina absent then

**Comment by Extra-Special-K** [comment]
Im also getting the same issue with Neruina, will hard crash my server when some people join or tp but not all the time. Crash reports here.

[crash-2025-06-16_18.51.15-server.txt](https://github.com/user-attachments/files/20765004/crash-2025-06-16_18.51.15-server.txt)

[crash-2025-06-16_18.55.00-server.txt](https://github.com/user-attachments/files/20765007/crash-2025-06-16_18.55.00-server.txt)

**Comment by Bawnorton** [comment]
This isn't neruina's fault your server is hanging because bumblezone is trying to get a block in a chunk but it's taking longer than 60s as it's blocked, why it's blocked is not clear and won't be without a thread dump but I doubt this is uniquely their fault, remove neruina and when it crashes again send them the report

**Comment by Extra-Special-K** [comment]
Ye just removed will attempt to recreate the crash now

**Comment by Extra-Special-K** [comment]
Okay yeah used offline tp to put myself where the crash was occurring and yeah still crashing without Neruina, here is the new crash report. Is there a way to solve this without removing bumblezone? because that would be a little depressing lol 

[crash-2025-06-16_23.31.03-server.txt](https://github.com/user-attachments/files/20765302/crash-2025-06-16_23.31.03-server.txt)

**Comment by Bawnorton** [comment]
Just report to the bumblezone and see what comes of it

**Comment by Bawnorton** [comment]
upon looking closer the 3rd crash was not caused by the bumblezone at all, in fact it was caused by no mod.

It's blocked by the worldgen thread. But again with no indication of why exactly

```
"Worker-Main-34" daemon prio=4 Id=381 RUNNABLE
	at java.base@17.0.15/java.util.ImmutableCollections$Set12.contains(ImmutableCollections.java:810)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.level.levelgen.SurfaceRules$BiomeConditionSource$$Lambda$74336/0x0000704f5826d310.test(Unknown Source)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.core.Holder$Reference.m_203425_(Holder.java:166)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.level.levelgen.SurfaceRules$BiomeConditionSource$1BiomeCondition.m_183479_(SurfaceRules.java:617)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.level.levelgen.SurfaceRules$LazyCondition.m_183475_(SurfaceRules.java:245)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.level.levelgen.SurfaceRules$TestRule.m_183550_(SurfaceRules.java:376)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.level.levelgen.SurfaceRules$SequenceRule.m_183550_(SurfaceRules.java:388)
	at TRANSFORMER/terrablender@3.0.1.10/terrablender.worldgen.surface.NamespacedSurfaceRuleSource$NamespacedRule.m_183550_(NamespacedSurfaceRuleSource.java:67)
	...
```
