### ISSUE TITLE
Crash due to incorrect java verson

### ISSUE THREAD

**Issue by atriup** [Benjamin-Norton/Neruina#84]
Using 1.20.4 with java 17 and fabric on linux

[This version](https://modrinth.com/mod/neruina/version/2.1.0-fabric+1.20.6 ) of neurina says on modrinth that it supports 1.20.4 - 1.20.6, but 1.20.4 uses java 17 while 1.20.5 and 1.20.6 use java 21. This causes a [crash](https://mclo.gs/XkSRfnU) due to the class file versions not matching (65 for java 21 and 61 for java 17). If this isn't an issue on my part, then the obvious solution would be adding 1.20.4 to the 1.20.1 - 1.20.3 release so there would be two releases: 1.20.1 - 1.20.4 and 1.20.5 - 1.20.6. Idk much about the differences between 1.20.3 and 1.20.4 so i'm not sure if there's a good reason it's like this.

**Comment by Bawnorton** [comment]
Typo in my build script. Should be 1.20.1-.4 and 1.20.5-.6 as separate jars. Thanks for noticing
