### ISSUE TITLE
Problème kick player

### ISSUE THREAD

**Issue by clemeta111** [Benjamin-Norton/Neruina#85]
Bonjour, 
J'ai un serveur aternos avec des amis sur lequel est installé neruina et quelque fois il y a eu des beug mais rien de plus je me téléporte pour voir ce que c'est et puis je la tue, la le problème apparaît, je m'y téléporte un peu au dessus de moi c'était un mouche, j'appuie sur tuer et la ça me fait quitter le serv, je me dis zut il a crash, mais nan après deux essais il m'explique que l'entité qui beugait c'est moi et donc je me suis kick sauf que je ne peut plus revenir sur mon serveur. Ducoup j'en crée un autre sur lequel j'installe le même modpack et sur lequel j'upload la Map sauf que ça continue de m'afficher "java.net.socketextension connection reset" comme sur l'ancien serveur. Lorsque je me connecte ça charge comme d'habitude: joining World puis loading terrain puisle message d'erreur et dans le chat ingame il y a écrit que neruina m'a kick pour chepaquoi, en fait je comprend pas comment fonctionne le mod est ce que il est possible que je retourne de nouveau sur mon serveur.
Merci

**Comment by Bawnorton** [comment]
I can't read french very well but I'm gonna need a log https://docs.fabricmc.net/players/troubleshooting/uploading-logs

**Comment by clemeta111** [comment]
Thanks for your answers so i didn't find the logs but i have an picture of the message of neruina when i try to join the server.
![image0 (1)](https://github.com/Bawnorton/Neruina/assets/84526479/f01044c1-adf1-4056-ab69-fb4cf873b97d)

**Comment by Bawnorton** [comment]
That is the log, can you send all of it

**Comment by clemeta111** [comment]
where can i find with aternos because the problem was yetersday

**Comment by Bawnorton** [comment]
I have no idea, look it up or recreate what caused it in the first place

**Comment by clemeta111** [comment]
thank you very much for your help we change the backup and lose some contruction but it reworks good.
Thank you
