### ISSUE TITLE
1.20.1 Nyf's Spiders by Nyfaria 

### ISSUE THREAD

**Issue by Krimatoria** [Benjamin-Norton/Neruina#87]
Oh, you've done auto-reports, how cool it is. But for now I decided to try copying the event. Is this the same thing or is it different from automatically creating a response?

Nyf's Spiders 2.1.1
https://modrinth.com/mod/nyfs-spiders
![image](https://github.com/user-attachments/assets/0ce1f863-8659-4f80-a90e-b9b68950e4e9)

> java.lang.NullPointerException: Cannot read the array length because "pathableFacings" is null
> 	at TRANSFORMER/nyfsspiders@2.1.1/com.nyfaria.nyfsspiders.common.entity.movement.AdvancedWalkNodeProcessor.getDirectionalPathNodeType(AdvancedWalkNodeProcessor.java:951)
> 	at TRANSFORMER/nyfsspiders@2.1.1/com.nyfaria.nyfsspiders.common.entity.movement.AdvancedWalkNodeProcessor.getDirectionalPathNodeType(AdvancedWalkNodeProcessor.java:933)
> 	at TRANSFORMER/nyfsspiders@2.1.1/com.nyfaria.nyfsspiders.common.entity.movement.AdvancedWalkNodeProcessor.m_8086_(AdvancedWalkNodeProcessor.java:929)
> 	at TRANSFORMER/nyfsspiders@2.1.1/com.nyfaria.nyfsspiders.common.entity.movement.ClimberMoveController.isWalkableAtOffset(ClimberMoveController.java:276)
> 	at TRANSFORMER/nyfsspiders@2.1.1/com.nyfaria.nyfsspiders.common.entity.movement.ClimberMoveController.m_8126_(ClimberMoveController.java:68)
> 	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.entity.Mob.m_6140_(Mob.java:772)
> 	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.entity.LivingEntity.m_8107_(LivingEntity.java:2548)
> 	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.entity.Mob.m_8107_(Mob.java:536)
> 	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.entity.monster.Monster.m_8107_(Monster.java:42)
> 	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.entity.LivingEntity.m_8119_(LivingEntity.java:2298)
> 	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.entity.Mob.m_8119_(Mob.java:337)
> 	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.entity.monster.Spider.m_8119_(Spider.java:79)
> 	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.level.ServerLevel.m_8647_(ServerLevel.java:693)
> 	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.level.Level.mixinextras$bridge$accept$142(Level.java)
> 	at TRANSFORMER/neruina@2.1.0/com.bawnorton.neruina.handler.TickHandler.safelyTickEntities(TickHandler.java:92)
> 	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.level.Level.wrapOperation$cib000$neruina$catchTickingEntities$notTheCauseOfTickLag(Level.java:3040)
> 	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.level.Level.m_46653_(Level.java:479)
> 	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.level.ServerLevel.m_184063_(ServerLevel.java:343)
> 	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.level.entity.EntityTickList.m_156910_(EntityTickList.java:54)
> 	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.level.ServerLevel.m_8793_(ServerLevel.java:323)
> 	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:893)
> 	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:814)
> 	at TRANSFORMER/minecraft@1.20.1/net.minecraft.client.server.IntegratedServer.m_5705_(IntegratedServer.java:89)
> 	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:661)
> 	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:251)
> 	at java.base/java.lang.Thread.run(Unknown Source)
>

**Comment by Bawnorton** [comment]
Report to nyf's spiders
