### ISSUE TITLE
Unable to join back to a server after being kicked due to a ticking exception

### ISSUE THREAD

**Issue by camclerk** [Benjamin-Norton/Neruina#88]
Hi, me and a few friends have a minecraft server and I got kicked when i fell in lava and the message "you have been kicked for a ticking exception on your player". I am still 5 days later unable to join, just wondering if there is a fix for this. Thanks!

**Comment by Bawnorton** [comment]
Share your log, this is Neruina behaving as expected and stopping your server from crashing from another mod.

**Comment by camclerk** [comment]
Hi,

thanks for getting back so fast, ive attached the latest log to the server.

Regards,

Cameron

**Comment by Bawnorton** [comment]
Emails don't forward attachments. Drag and drop the file onto a new comment

**Comment by camclerk** [comment]
[latest.log](https://github.com/user-attachments/files/16337997/latest.log)

**Comment by Bawnorton** [comment]
Report to friends and foes
