### ISSUE TITLE
Crash due to tick issue 

### ISSUE THREAD

**Issue by WhiteOakMbzTO** [Benjamin-Norton/Neruina#89]
uploaded it to a txt file cus its too long
[server logs.txt](https://github.com/user-attachments/files/16388014/server.logs.txt)

**Comment by Bawnorton** [comment]
Server took too long to process a tick, it's hung on calculating whether a zombie can breathe underwater. 
This is not related to Neruina, follow these instructions:
```
// This modpack was created by Lunapixel Studios. To resolve this crash, please join discord.gg/lunapixel and read the #get-support Discord channel.
```
