### ISSUE TITLE
Crash while trying to create a new world [Fabric 1.21]

### ISSUE THREAD

**Issue by mpustovoi** [Benjamin-Norton/Neruina#91]
The logs say that there is no method in Neruina, although I don't think that's the problem. I can't figure it out myself.
[Logs](https://mclo.gs/jJ9dhme) and [crash-report](https://mclo.gs/HnCmezb)

**Comment by Bawnorton** [comment]
No idea what caused this, but I know it wasn't Neruina as Neruina doesn't affect world gen.

**Comment by mpustovoi** [comment]
The problem was related to the Collective mod. It was broken with v7.79 which was later taken down, and I couldn't update it in Modrinth App.
