### ISSUE TITLE
[Fabric 1.20.4] Crash when entering singleplayer world

### ISSUE THREAD

**Issue by Franco227** [Benjamin-Norton/Neruina#95]
Minecraft crashes whenever entering any singleplayer world.

Logs: https://mclo.gs/NZSf6Oq
Minecraft 1.20.4
Fabric Loader 0.16.2
Neruina [2.1.1+1.20.1](https://github.com/Bawnorton/Neruina/releases/tag/fabric-2.1.1%2B1.20.1)

**Comment by Bawnorton** [comment]
1.20.4 is no longer supported; build is broken and low demand
