### ISSUE TITLE
Fabric 1.20.1 (i played fabric fantasy minecraft) Ticking Execption Issue

### ISSUE THREAD

**Issue by AnomaliMei** [Benjamin-Norton/Neruina#96]
so the story is that when I wanted to play this mod while installing the replay mod, suddenly when I checked the replay mod, suddenly I immediately came out and there was a Ticking Execption notification "nerunia caught a ticking exception on your client, see your logs more info" please tell me how to fix it, do i have to delete some mods?? if yes what is it

thanks for helping me :)

![2024-08-17_11 35 35](https://github.com/user-attachments/assets/37e51864-3dfd-49c6-882e-bd68a948f017)

**Comment by Bawnorton** [comment]
Please can you send your logs
