### ISSUE TITLE
1,20,1 fabric

### ISSUE THREAD

**Issue by zc1108aaa** [Benjamin-Norton/Neruina#97]
[Uploading latest - 副本.log…]()

**Comment by zc1108aaa** [comment]
[latest - 副本.log](https://github.com/user-attachments/files/16750581/latest.-.log)

**Comment by Bawnorton** [comment]
Theres no crash here, what's the issue?

**Comment by zc1108aaa** [comment]
Unable to create map

**Comment by Bawnorton** [comment]
What? I don't see how this is related to neruina
