### ISSUE TITLE
(question)

### ISSUE THREAD

**Issue by Emperor339** [Benjamin-Norton/Neruina#98]
Good afternoon, I really like how this mod sounds, but the part where it says "If another mod causes the Player to crash on tick, the Player will be kicked instead" worries me that it might kick my friends. On my server, I disabled "max-tick-time=-1" by setting it to -1. I also have many mods with large structures that lag the server for 1 to 3 minutes until they load. I'm still new to this, and honestly, I don't fully understand how this mod works. My only concern, based on what I'm reading, is that it might constantly kick my friends.

**Comment by Bawnorton** [comment]
That's not a Neruina setting. The only reason a player would be kicked is that if they weren't the server would crash, which is worse than just being kicked. It's rare that it happens, if it does feel free to make a new issue here and I can try to help you diagnose what happens and what needs fixing

**Comment by Emperor339** [comment]
Thank you very much for your response. I will make a backup and run tests on the server

**Comment by Emperor339** [comment]
> That's not a Neruina setting. The only reason a player would be kicked is that if they weren't the server would crash, which is worse than just being kicked. It's rare that it happens, if it does feel free to make a new issue here and I can try to help you diagnose what happens and what needs fixing

I didn't notice any changes; the server is working fine and it's not giving me any kind of problem. I don't fully understand the mod. Does "Entity will be suspended" or "Item will stop" mean that it pauses until the server stabilizes or something like that? And then the block or entity resumes functioning normally?

**Comment by Bawnorton** [comment]
If an entity or item would crash the server, it's suspended, meaning it won't tick, neruina will inform you and provide actions on what to do if it happens. 99% of the time you don't need to worry about this mod, the 1% where it does matter you'll be very glad you have it; without it you will not be able to recover your world without modifying region files. I have a wiki page explaining exactly what this mod is and how it works https://github.com/Bawnorton/Neruina/wiki/What-Is-This%3F

**Comment by Emperor339** [comment]
Thanks a lot!
